     <div class="fl-cnt-50">
      <p>&copy; 2012 SLEPICE / ZF</p>
     </div>
     <div class="fl-cnt-50">
      <ul>
        <li><a href="/" title="FLO~ Homepage">Home</a></li>
        <li><a href="/help" title="Help section">FAQs</a></li>
        <li><a href="/about-us" title="Manifesto">Manifesto</a></li>
        <li><a href="/index/privacy" title="Terms &amp; Conditions">Terms &amp; Conditions</a></li>
        <li class="divider"></li>
        <li><a href="/member/index/sign-up" title="Sign Up">Sign Up</a></li>
        <li><a href="/member/index/login" title="Log In">Log In</a></li>
      </ul>      
     </div>