     <div class="fl-cnt-50">
      <p>&copy; 2012 SLEPICE / ZF</p>
     </div>
     <div class="fl-cnt-50">
      <ul>
        <li><a href="/" title="FLO~ Homepage">Home</a></li>
        <li><a href="/help" title="Help section">FAQs</a></li>
        <li><a href="/about-us" title="Manifesto">Manifesto</a></li>
        <li><a href="/index/privacy" title="Terms &amp; Conditions">Terms &amp; Conditions</a></li>
        <li class="fl-rss-link"><a href="">RSS</a></li>
        <li class="divider"></li>
        <li><a href="/member/index/sign-up" title="Sign Up">Sign Up</a></li>
        <li><a href="/member/index/login" title="Log In">Log In</a></li>
      </ul>      
     </div>

     <?php 
     	$content = "";
       foreach($this->categories as $c){ 
       	$content .= '<a style="color:white" href="/rss?category='.$c->id.'">'.$c->name.'</a>  '; } 
     ?>

     <script src="/media/jquery.simpletip-1.3.1/jquery.simpletip-1.3.1.js"></script>
     <script>

       $(document).ready(function(){

        var li = $('.fl-rss-link');
        var position = ["-350", "-50"];
        var content = '<div class="rss-tooltip-in"><?php echo $content; ?></div><div class="rss-tooltip-arrow"></div>';
        $(li).simpletip({
          baseClass: 'fl-simpletip-tooltip',
          activeClass: 'fl-simpletip-rss',
          position: position,
            offset: [0, -5],
            content: content,
            hideEffect: 'none',
        });

        });

     </script> 