<div class="row">
   <div class="span5 offset6">
   
     <form class="form-inline fl-search fl-top" method="get" action="/browse-projects">
       <label for="fl_search" class="hide">Search:</label>
       <div class="input-prepend input-append">
         <span class="add-on"><i class="icon-search"></i></span><input id="fl_search" name="q" type="text"><button type="submit" class="btn">Search</button>
       </div>
     </form>
     
     </div>
   </div>
   
   <div class="row">
     <div class="span3">
        <h1><a href="/" title="FLOW - Start.Build.Lead.Grow.">FLOW PLATFORM<span></span></a></h1>
     </div>
   </div>
   
   <div class="row">
     <div class="span8">
     
         <ul class="nav nav-pills fl-menu">
           <li><a href="/" title="">Home</a></li>
           <li><a href="/browse-projects" title="">Browse Projects</a></li>
           <li><a href="/browse-members" title="">Browse Users</a></li>
           <li><a href="/help" title="">FAQs</a></li>
           <li><a href="/about-us" title="">Manifesto</a></li>
         </ul>
   </div>
     <div class="span3">
    <!-- User -->
       <?php if($this->isLogged) {?>
       <ul class="nav nav-pills fl-user-menu">
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">  
                  <img src="<?php echo $this->loggedMember->getProfilePictureUrl("tiny").'?foo='.time()?>" 
                  alt="<?= $this->loggedMember->name;?>" width="25" height="25" alt="" class="fl-menu-img"/> 
                  <?= $this->loggedMember->email;?> <b class="caret"></b></a>
              <ul class="dropdown-menu fl-width100">
                <li><a href="/member/dashboard" title="My dashboard">My dashboard</a></li>
                <li><a href="/member/profile/index/id/<?= $this->loggedMember->id;?>" title="My profile">My profile</a></li>
                <li><a href="/member/profile-setting/member-info" title="Edit my profile">Edit my profile</a></li>
                <?php if ($this->isAdmin){?>
                	<li class="divider"></li>
               		<li><a href="/admin" title="Admin zone">Admin Zone</a></li> 
                <?php }?>
               	 <li class="divider"></li>
                <li><a href="/member/index/logout" title="Log out">Log out</a></li>
              </ul>
            </li>
          </ul>
       <?php }else{?>
         <!-- Visitor -->
         <div class="fl-user-menu">
           <div class="input-append input-prepend">
             <a href="/member/index/sign-up" class="btn">Sign up for FLO~</a><a href="/member/index/login" class="btn btn-info"><i class="icon-lock icon-white"></i> Log in</a>
           </div>
         </div>

       <?php }?>
     </div>
     
   </div>