<h2>Learn More</h2>

<div class="cnt-100">
<p>Coming Soon: A visual overview of the FLO~ process & a primer on Lean....In the meantime, check out these links to get best informed:</p>
<ul class="lp-further">
  <li>Newsletter I: <a href="http://floplatform.com/newsletters/1.html" title="Newsletter I: What We Are">What We Are</a></li>
  <li>Newsletter II: <a href="http://floplatform.com/newsletters/2.html" title="Newsletter II: How We Work">How We Work</a></li>
  <li>The FLO~ <a href="http://floplatform.tumblr.com/post/23994542145/the-manifesto" title="The FLO~ Manifesto">Manifesto</a></li>
</ul> 
</div>