<h3>Browse Members <?php echo $this->query;?></h3>
<hr>
<div class="well"><?php echo $this->debug;?></div>
<div class="fl-cnt-100"> 
<?php echo $this->form; ?>
</div>

<hr>
<!-- Project Displaying -->
<?php if (count($this->paginator)) {?>
<?php echo $this->paginationControl($this->paginator, 'Elastic', 'partials/pagination-control-bootstrap.phtml'); ?> 

	<ul class="thumbnails">
    <?php foreach ($this->paginator as $user){ ?> 
       
        <li class="span3 fl-thumbnail-frame">
                  <div class="thumbnail">
                   <a href="<?php echo $user->getProfileUrl();?>"> 
                     <img src="/storage/users/<?php echo $user->getProfilePicture()?>" alt="<?php echo $user->getName(); ?>">
            		 </a>      
                     <h3><?php echo $user->name?></h3>
                     <div class="fl-cnt-100">
                       <span class="author"><i class="icon-user"></i> <?php echo $user->name?></span>
                       <p class="info">
                         <span class="followers"><i class="icon-eye-open"></i><strong class="follower-count"><?php echo $user->getCountFriendsWithMe();?></strong> followers</span>
                         <span class="like"><i class="icon-thumbs-up"></i> 
                         <?php
                         // like dislike solution 
                         if(!$user->isFriendWithMe($this->loggedMember)) {
						 ?> <a href="" title="" class="like-member" id="<?php echo $user->id;?>" >Like</a>
						 <?php } else { ?>
                            <a href="" title="" class="like-member" id="<?php echo $user->id;?>" >Dislike</a>
                         <?php } ?>
                         </span>
                       </p>
                        <div class="fl_project_thumb_roles">
                         	<?php $specRoles = $user->getSpecificRoles();
								foreach ($specRoles as $r){?>     
                       		 	 <div class="fl_project_thumb_role">
		                           	<img src="/media/slepice-site/1.0.0/img/role_<?php echo $r->name;?>.png" alt="<?php echo $r->name;?>" title="<?php echo $r->name;?>" />
		                         </div>                	
                      	<?php } ?>     
                       </div>         
                     </div>
                  </div>   
                </li>
    <?php } ?>
  </ul>			
  <?php } else echo "There are no users."?>

 <script type="text/javascript">  
			var Models = {
			init: function(config){
				// ajax setup
				$.ajaxSetup({
					url: "/site/index/ajax-index", 
					type: 'GET',
					dataType: 'json',
				});
				
				this.config = config;
				this.bindEvents();
			},
				
			bindEvents: function(){
				//this.config.likeMemberBtn.css("color","red");
				this.config.likeMemberBtn.on("click", this.likeMember);		
			},
				
			// likeMember
			likeMember: function(e) {
				var follower_count = $(this).closest('.info').find(".follower-count");
				console.log(follower_count);
				var val = $(this).text();
				var user_id = $(this).attr("id");
				if(val == 'Like') {
					$(this).html("Dislike");
				}else {
					$(this).html("Like");
				} 	
					// send data to server
					$.ajax({
						data:   "&_method=like-member&&friend_id="+user_id, // take data from the form and send it to the method update
					}).done(
							function (results){
								// set new value for followers		
								follower_count.html(results.data.count_friends); // number of current friends
							}
					);			
				e.preventDefault();
			}

			};

			
			
			// like models
			Models.init({
				likeMemberBtn: $(".like-member"), //select a with class 
			});
 </script>  
  
      
    	