<h3>Browse Members <?php echo $this->query;?></h3>
<hr>
<div class="well"><?php echo $this->debug;?></div>
<div class="fl-cnt-100"> 
<?php echo $this->form; ?>
</div>

<hr>
<!-- Project Displaying -->
<?php if (count($this->paginator)) {?>
<?php echo $this->paginationControl($this->paginator, 'Elastic', 'partials/pagination-control-bootstrap.phtml'); ?> 

	<ul class="thumbnails">
    <?php foreach ($this->paginator as $user){ ?> 
       
        <li class="span3 fl-thumbnail-frame">
                  <div class="thumbnail">
                   <a href="<?php echo $user->getProfileUrl();?>"> 
                     <img src="/storage/users/<?php echo $user->getProfilePicture()?>" alt="<?php echo $user->getName(); ?>">
            		 </a>      
                     <h3><?php echo $user->name?></h3>
                     <div class="fl-cnt-100">
                       <span class="author"><i class="icon-user"></i> <?php echo $user->name?></span>
                       <p class="info">
                         <span class="followers"><i class="icon-eye-open"></i><strong class="follower-count"><?php echo $user->getCountFriendsWithMe();?></strong> followers</span>
                         <span class="like"><i class="icon-thumbs-up"></i> 
                         <?php
                         // like dislike solution 
                         if(!$user->isFriendWithMe($this->loggedMember)) {
						 ?> <a href="" title="" class="like-member" id="<?php echo $user->id;?>" >Like</a>
						 <?php } else { ?>
                            <a href="" title="" class="like-member" id="<?php echo $user->id;?>" >Dislike</a>
                         <?php } ?>
                         </span>
                       </p>
                        <div class="fl_project_thumb_roles">
                         	<?php $specRoles = $user->getSpecificRoles();
								foreach ($specRoles as $r){?>     
                       		 	 <div class="fl_project_thumb_role">
		                           	<img src="/media/slepice-site/1.0.0/img/role_<?php echo $r->name;?>.png" alt="<?php echo $r->name;?>" title="<?php echo $r->name;?>" />
		                         </div>                	
                      	<?php } ?>     
                       </div>         
                     </div>
                  </div>   
                </li>
    <?php } ?>
  </ul>			
  <?php } else echo "There are no users."?>

<script src="<?=$this->baseUrl('/media/slepice-site/1.0.0/js/like-member-project-1.0.0.js')?>"></script> 
       
    	