<div class="row">
 <div class="span9">

<h2>Browse projects <?php echo $this->query;?></h2>

<div class="fl-cnt-100"> 
<?php echo $this->form; ?>
</div>

<div class="fl-cnt-100"> 
  <div class="fl-filtr-form">
    <form>
      <fieldset>
        <legend class="hide">Browse projects: </legend>

        <div class="fl-width100">
          <div class="fl-width25 left">
            <label for="" class="hide">Category:</label>
            <select name="" class="fl-width100 fl-margin0">
              <option value="">All</option>
              <option value="">All</option>
              <option value="">All</option>
              <option value="">All</option>
            </select>
          </div>

          <div class="fl-width75 right">
            <label for="" class="hide">Text:</label>
            <div class="input-append fl-filtr-search">
              <input type="text" name="" id="" class="fl-width85"/><input type="submit" class="btn btn-info fl-width30" value="search" />
            </div>
          </div>
        </div>

        <div class="fl-width100">
          <div class="hide">
            <label for="role_starter">
              <input type="checkbox" name="role_starter" id="role_starter" /> starter
            </label>
            <label for="role_leader">
              <input type="checkbox" name="role_leader" id="role_leader" /> leader
            </label>
            <label for="role_grower">
              <input type="checkbox" name="role_grower" id="role_grower" /> grower
            </label>
            <label for="role_builder">
              <input type="checkbox" name="role_builder" id="role_builder" /> builder
            </label>
            <label for="role_adviser">
              <input type="checkbox" name="role_adviser" id="role_adviser" /> adviser
            </label>
          </div>
          <div class="fl-width33 left fl-top10">
            Choose available roles:
            <ul id="fl-filtr-form-choose-role">
              <li><img src="/media/slepice-site/1.0.0/img/role_starter.png" id="role_starter" alt="role_starter" /></li>
              <li><img src="/media/slepice-site/1.0.0/img/role_leader.png" id="role_leader" alt="role_leader" /></li>
              <li><img src="/media/slepice-site/1.0.0/img/role_grower.png" id="role_grower" alt="role_grower" /></li>
              <li><img src="/media/slepice-site/1.0.0/img/role_builder.png" id="role_builder" alt="role_builder" /></li>
              <li><img src="/media/slepice-site/1.0.0/img/role_adviser.png" id="role_adviser" alt="role_adviser" /></li>
            </ul>
          </div>

          <div class="fl-filtr-form-project-level">
            Select project level:
            <div class="fl-width100 fl-top5">
              <div class="fl-width80 left">
                <label for="" class="hide">Sign:</label>
                <select name="" id="" class="fl-filtr-form-sign">
                  <option value="">equal</option>
                  <option value="">greater than</option>
                  <option value="">less than</option>
                </select>
              </div>
              <div class="fl-width20 left">
                <label for="" class="hide">Project level:</label>
                <select name="" id="" class="fl-filtr-form-level">
                  <option value="1">1</option>
                  <option value="2">2</option>
                  <option value="3">3</option>
                </select>
              </div>
            </div>
          </div>

          <div class="fl-filtr-form-passion-level">
            Select level of passion:
          </div>

        </div>
      </fieldset>
    </form>
  </div>
</div>

<div class="fl-cnt-100">
  Total results: 56 projects
</div>


<div class="fl-cnt-100">
<!-- Project Displaying -->
<?php echo $this->paginationControl($this->paginator, 'Elastic', 'partials/pagination-control-bootstrap.phtml'); ?> 
</div>

<div class="fl-cnt-100">
    <?php if (count($this->paginator)) {?>
   <ul class="thumbnails">
    <?php foreach ($this->paginator as $project){ ?>

    	
        <li class="span3 fl-thumbnail-frame">
                  <div class="inner-5">

                     <a href="/project/index/index/id/<?php echo $project->id?>" title="<?php echo $project->title; ?>"> 
                        <img alt="<?php echo $project->title; ?> - main picture" src="/storage/projects/<?php echo $project->dir."/".$project->getPicture('large'); ?> " />
                     </a>

<?php switch($project->level){
  case '1': ?>
                     <div class="fl-level">
                        <div class="progress">
                          <div class="fl_level1"></div>
                        </div>
                        <div class="progress">
                          <div class="bar"></div>
                        </div>
                        <div class="progress">
                          <div class="bar"></div>
                        </div>
                      </div>
<?php ; break;
  case '2': ?>

                      <div class="fl-level">
                        <div class="progress">
                          <div class="fl_level2"></div>
                        </div>
                        <div class="progress">
                          <div class="fl_level2"></div>
                        </div>
                        <div class="progress">
                          <div class="bar"></div>
                        </div>
                      </div>
<?php ; break;
  case '3': ?>
                      <div class="fl-level">
                        <div class="progress">
                          <div class="fl_level3"></div>
                        </div>
                        <div class="progress">
                          <div class="fl_level3"></div>
                        </div>
                        <div class="progress">
                          <div class="fl_level3"></div>
                        </div>
                      </div>
<?php ;
}?>
                     
                     <h3><?php echo $project->title; ?></h3>
                     
                     <div class="fl-cnt-100">
                       <span class="author"><i class="icon-user"></i> <a href="" title=""><?php echo $project->user->name?></a></span>
                       <div class="fl-cnt-100 fl-height-60">
                         <p><?php echo shorter($project->pitchSentence, 100); ?></p>
                       </div>
                       <p class="info">
                         <span class="category"><i class="icon-folder-close"></i> <?php echo $project->category->name?></span>
                         <span class="followers"><i class="icon-eye-open"></i> <strong class="follower-count"><?php echo $project->getCountFollowers();?></strong>  followers</span>
                          <span class="like"><i class="icon-thumbs-up"></i> 
                         <?php
                         // like dislike solution 
                         if(!$project->isFollower($this->loggedMember)) {
						 ?> <a href="" title="" class="like-project" id="<?php echo $project->id;?>" >Like</a>
						 <?php } else { ?>
                            <a href="" title="" class="like-project" id="<?php echo $project->id;?>" >Dislike</a>
                         <?php } ?>
                         </span>
                       </p>
                     </div>
                  </div>
                      
                     <div class="fl-cnt-100 fl-thumb-roles">
                       <div class="fl_project_thumb_roles">
                         <div class="fl_project_thumb_role">
                           <img src="/media/slepice-site/1.0.0/img/role_starter.png" alt="" />
                         </div>
                         <div class="fl_project_thumb_role">
                           <img src="/media/slepice-site/1.0.0/img/role_starter.png" alt="" />
                         </div>
                         <div class="fl_project_thumb_role">
                           <img src="/media/slepice-site/1.0.0/img/role_starter.png" alt="" />
                         </div>
                         <div class="fl_project_thumb_role">
                           <img src="/media/slepice-site/1.0.0/img/role_starter.png" alt="" />
                         </div>
                       </div>
                     </div>
                </li>
    <?php } ?>
  </ul>

    <?php } else echo "There are no projects for this search."?>
      </div>

</div>
	   
	  <div class="span2">	    
	    <!-- Category menu and filters module -->
	  	<?= $this->action('category', 'widget', 'site');  ?>
       </div>
  
    </div>
  </div>
    
<script src="<?=$this->baseUrl('/media/slepice-site/1.0.0/js/choose-role.js')?>"></script>        
<script src="<?=$this->baseUrl('/media/slepice-site/1.0.0/js/like-member-project-1.0.0.js')?>"></script> 
 

    
