<div class="row">
 <div class="span9">

<h2>Browse projects <?php echo $this->query;?></h2>

<?php 
// when the most-viewed, recommened, .. is selected don't display search form
if ($this->displayForm) {?>
<div class="fl-cnt-100"> 
  <div class="fl-filtr-form">
    <form action="<?= $this->form->getAction(); ?>" method="<?= $this->form->getMethod(); ?>" id="form-browse-projects">
      <fieldset>
        <legend class="hide">Browse projects: </legend>

        <div class="fl-width100">
          <div class="fl-width25 left">
          <?php echo $this->form->category?>
          </div>

          <div class="fl-width75 right">
            <label for="" class="hide">Keyword:</label>
            <div class="input-append fl-filtr-search">
             <?php echo $this->form->q;?><input type="submit" class="btn btn-info fl-width30" value="search" />
            </div>
          </div>
        </div>

        <div class="fl-width100">
          <div class="hide">
          	<?php echo $this->form->project_role;?>
          </div>
          <div class="fl-width33 left fl-top10">
            Choose available roles:
            <ul id="fl-filtr-form-choose-role">
              <li><img src="/media/slepice-site/1.0.0/img/role_starter.png" id="project_role-starter" alt="role_starter" /></li>
              <li><img src="/media/slepice-site/1.0.0/img/role_leader.png" id="project_role-leader" alt="role_leader" /></li>
              <li><img src="/media/slepice-site/1.0.0/img/role_grower.png" id="project_role-grower" alt="role_grower" /></li>
              <li><img src="/media/slepice-site/1.0.0/img/role_builder.png" id="project_role-builder" alt="role_builder" /></li>
              <li><img src="/media/slepice-site/1.0.0/img/role_adviser.png" id="project_role-adviser" alt="role_adviser" /></li>
            </ul>
          </div>

          <div class="fl-filtr-form-project-level">
            <div class="fl-width100">
              <div class="fl-width100 left">
                <?php echo $this->form->level;?>
              </div>
            </div>
          </div>

          <div class="fl-filtr-form-passion-level">
                <div class="fl-width100">
             <?php echo $this->form->priority;?>
             </div>
          </div>
        </div>
      </fieldset>
    </form>
  </div>
</div>
<?php 
}
?>


  
<div class="fl-cnt-100 fl-top20">
  		<strong>Total results:</strong> <?php echo $this->paginator->getTotalItemCount();?> projects
</div>


<div class="fl-cnt-100 fl-top20">
<?php if (count($this->paginator) > 1 )echo $this->paginationControl($this->paginator, 'Elastic', 'partials/pagination-control-bootstrap.phtml'); ?> 
</div>

<div class="fl-cnt-100">
    <?php if (count($this->paginator)) {?>
  
    
   <ul class="thumbnails">
    <?php foreach ($this->paginator as $project){ ?>

    	
        <li class="span3 fl-thumbnail-frame">
                  <div class="inner-5">
                     <a href="<?php echo $project->getProjectUrl();?>" title="<?php echo $project->title; ?>"> 
                        <img alt="<?php echo $project->title; ?> - main picture" src="<?php echo $project->getPictureUrl("medium");?>" />
                     </a>
 						<div class="fl-level">
                        <?php 
                        // Display Current Level
                        $array[1] = array('fl_level1','bar','bar');
                        $array[2] = array('fl_level2','fl_level2','bar');
                        $array[3] = array('fl_level3','fl_level3','fl_level3');
                        foreach($array[$project->level] as $c){ ?>
                                            <div class="progress">
                                                  <div class="<?php echo $c?>"></div>
                                            </div>
                        <?php } ?>
                        </div>
                     
                     <h3><?php echo $project->title; ?></h3>
                     
                     <div class="fl-cnt-100">
                       <span class="author"><i class="icon-user"></i> <a href="<?php echo $project->user->getProfileUrl(); ?>" title=""><?php echo $project->user->name?></a></span>
                       <div class="fl-cnt-100 fl-height-60">
                         <p><?php echo shorter($project->pitchSentence, 100); ?></p>
                       </div>
                       <p class="info">
                         <span class="category"><i class="icon-folder-close"></i> <?php echo $project->category->name?></span>
                         <span class="followers"><i class="icon-eye-open"></i> <strong class="follower-count"><?php echo $project->getCountFollowers();?></strong>  followers</span>
                          <span class="like"><i class="icon-thumbs-up"></i> 
                         <?php
                         // like dislike solution 
                         if(!$project->isFollower($this->loggedMember)) {
						 ?> <a href="" title="" class="like-project" id="<?php echo $project->id;?>" >Like</a>
						 <?php } else { ?>
                            <a href="" title="" class="like-project" id="<?php echo $project->id;?>" >Dislike</a>
                         <?php } ?>
                         </span>
                       </p>
                     </div>
                  </div>
                      
                     <div class="fl-cnt-100 fl-thumb-roles">
                        <div class="fl_project_thumb_roles">
                         <?php 
                       		 $display = false;
                        // if level 1 display all logos   
						if($project->level == 1) {
                        $freePositions = \App\Entity\ProjectRole::getRolesArray();
							$display = true;
						}
						if($project->level == 2){
                       // if level 2 display free positions
                        $facadeProject = new \App\Facade\Project\TeamFacade($this->em);
                    	$freePositions = $facadeProject->findFreeUniqueProjectRolesForProjectArray($project->id); 
							$display =  true;	
						}
						
						if($display){
						
                    	// if level 3 = have no idea what to display or not
                    	foreach ($freePositions as $r){
                    		
                    		echo '<div class="fl_project_thumb_role">';
                    		echo '<img src="/media/slepice-site/1.0.0/img/role_'.$r.'.png" alt="'.$r.'" title="'.$r.'" />';
                    		echo '</div>';
                    	}
						} 
                    	?>
                       </div>
                     </div>
                </li>
    <?php } ?>
  </ul>

    <?php } else echo "There are no projects for this search."?>
      </div>

  </div>
  <div class="span2">	    
  <!-- Category menu and filters module -->
	  <?= $this->action('category', 'widget', 'site');  ?>
  </div>
</div>

    
<script src="<?=$this->baseUrl('/media/slepice-site/1.0.0/js/choose-role.js')?>"></script>        
<script src="<?=$this->baseUrl('/media/slepice-site/1.0.0/js/like-member-project-1.0.0.js')?>"></script> 
 

    
