<div id="container-74-4">
      <div id="container-74-7">
        <div id="col-7"> 

<h2>Welcome back, <?php echo $this->loggedMember->name;?></h2>

              <div class="fl-cnt-100">
                <ul class="fl-dashboard">
                  <li><a href="/admin/project/index" title="Manage projects"><i class="fl-dashboard-icon-myprojects"></i> Browse Projects</a></li>
                  <li><a href="/admin/member/index" title="Manage members"><i class="fl-dashboard-icon-peopleilike"></i> Browse Members</a></li>
                  <li><a href="/admin/newsletter/index" title="Manage newsletter"><i class="fl-dashboard-icon-new"></i> Newsletters</a></li>
                  <li><a href="/admin/slideshow/index" title="Manage slideshow"><i class="fl-dashboard-icon-flobox"></i> Slideshow</a></li>
                </ul>
              </div>
  </div>

  <div id="col-4">
    <div class="inner">
    	<h3 class="fl-uppercase">Statistics</h3>
                <div class="fl_thick_divider"></div>
                
                <div class="fl-cnt-100">
                  <ul class="fl-ul-list-style-none">
                    <li>
                      <div class="fl-cnt-100">
                        <span class="fl-stat-overall"><?php echo $this->countUsers;?></span> 
                        <span class="fl-stat-overall-note">members</span>
                        
                      </div>
                      <div class="fl_thin_divider"></div>
                    </li>
                    <li>
                      <div class="fl-cnt-100">
                        <span class="fl-stat-overall"><?php echo $this->countProjects;?></span> 
                        <span class="fl-stat-overall-note">projects</span>
                        
                      </div>
                    </li>
                  </ul>
                </div>
    </div>
  </div>
  
</div>
</div>


