
<?php if($this->aclPermissionDenied) {echo'<div class="fl-cnt-100">You have alredy applied or you are in collaboration team.</div>'; return;}?>
<?php if($this->project->disableRoleWidget) { echo '<div class="fl-cnt-100">Widget for collaboration disabled</div>'; return;}?>
<?php if($this->project->level > 2) { echo '<div class="fl-cnt-100">Is not possible to apply for collaboration in this level.</div>'; return;}?>

<div class="fl-team-join-team">
  <div class="inner">
  	
<a data-toggle="modal" href="#modal-form-application" class="btn btn-primary fl-join-team-btn">
   <span class="fl-join-team-btn-join">join</span><br />
   <span class="fl-join-team-btn-label">this project</span>
</a>

  </div>
</div>

<div class="modal span8 hide" id="modal-form-application">
	<?php echo $this->form;?>
</div>

<div id='debug'></div>

<script type="text/javascript">

//wait for the DOM to be loaded 
$(document).ready(function() { 
	var form = $('#form-application');
	var myModal = $('#modal-form-application');

	form.validate({
	    		rules: {
	    			answer_1 :{
		    			required: true,
	    				minlength: 2
			    		},
			    	answer_2 :{
		    			required: true,
	    				minlength: 2
			    		},
			    	answer_3 :{
			    			required: true,
		    				minlength: 2
				    		},
				    answer_4 :{
				    			required: true,
			    				minlength: 2
					    		},
					answer_5 :{
					    			required: true,
				    				minlength: 2
						    		},
	    			content: {
	    				required: true,
	    				minlength: 2
	    			}
	    		},
	    		   submitHandler: function(form) {
		    		   form.submit();
				 		myModal.modal('hide');					 		    
			 		   }
	    	}
	   );	
    }); 
</script>

