<?php //if(!$this->isLogged) {echo'<div class="fl-cnt-100">You have to member if you wanna try to be part of team for this project.</div>'; return;}?>
<?php //if($this->aclPermissionDenied) { echo '<div class="fl-cnt-100">You have alredy applied or you are in collaboration team. </div>'; return;}?>
<?php //if($this->project->disableRoleWidget) { echo '<div class="fl-cnt-100">Widget for collaboration is disabled</div>'; return;}?>
<?php //if($this->project->level > 2) { echo '<div class="fl-cnt-100">Is not possible to apply for collaboration in this level.</div>'; return;}?>
<?php //if(empty($this->freePositions)) { echo ''; return;}?>


<?php 
// generate forms in cycle for all roles 
// get all roles which are in system

$allRoles = \App\Entity\ProjectRole::getRolesArray(); // array(starter, builder, ..)

foreach($allRoles as $currentRole){ 
	$count = 0; // number of free roles for current position
	// count roles 
	foreach ($this->freePositions as $p){
		if($p->name == $currentRole){
			$count++;
		}
	}
	
	// display form for current role with free positions
	if($count > 0){
		$s = '';
		if($count != 1){ $s = 's'; }
	?>	
		<div class="fl-cnt-100 fl-bottom5">
			<div class="fl-cnt-60">
			  <img src="/media/slepice-site/1.0.0/img/role_<?php echo $currentRole;?>.png" alt="<?php echo $currentRole;?>" /> <?php echo $count;?> free position<?php echo $s;?>
			</div>
			<div class="fl-cnt-40 text-right fl-top6">
				<a class="btn btn-info fl-width80" data-toggle="modal" href="#modal-form-application-level2-<?php echo $currentRole;?>">Apply for <?php echo $currentRole;?></a>
			</div>
		</div>

<div class="modal span7 hide" id="modal-form-application-level2-<?php echo $currentRole;?>">
 <?php 

 $form = new \App\Form\Project\AddProjectApplicationLevel2Form($this->member, $this->project, $this->freePositions, $currentRole);
 echo $form;
?>

<script type="text/javascript">
$(document).ready(function() { 
	var form = $('#form-application-level-2-<?php echo $currentRole;?>');
	var myModal = $('#modal-form-application-level2-<?php echo $currentRole;?>');

	form.validate({
	    		rules: {
	    			content: {
	    				required: true,
	    				minlength: 2
	    			}
	    		},
	    		   submitHandler: function(form) {
		    		   form.submit();
				 		myModal.modal('hide');					 		    
			 		   }
	    	}
	   );	
    }); 
</script>		
</div>
	<?php 	
		
	}
	
}

 ?>

 


