      <!-- Detail about author -->
       <div class="fl-cnt-project-by">
                <h3 class="fl-cnt-project-by-h3">Project by</h3>
                <div class="fl_thick_divider"></div>
                <div class="fl-cnt-project-by-content">
                  <div class="inner">
                    <div class="fl-cnt-project-by-content-left">
                      <img src="<?php echo $this->project->user->getProfilePictureUrl('big');?>" alt="" title="" class="fl-cnt-project-by-author-photo"/>
                      
                      <div class="fl-cnt-project-by-content-skills">

<?php $specRoles = $this->project->user->getSpecificRoles();
foreach ($specRoles as $r){?>
								<div class="fl-cnt-project-by-content-skill">
                  <img src="/media/slepice-site/1.0.0/img/role_<?php echo $r->name;?>.png" alt="<?php echo $r->name;?>" title="<?php echo $r->name;?>" />
                  <span class="fl-cnt-project-by-content-skill-role"><?php echo $r->name;?></span><br />
                  <span class="fl-cnt-project-by-content-skill-tag"><?php echo $r->getTagsString();?></span>
                </div>                      	
<?php }	?>
                      </div>        
                      <div class="fl_thick_divider"></div>
                      <div class="fl-cnt-project-by-content-earned-role">
                        <img src="/media/slepice-site/1.0.0/img/role40x40_6.png" alt="" title="earned role" />
                      </div>
                    </div>
                    <div class="fl-cnt-project-by-content-right">
                      <div class="fl-cnt-project-by-content-inner">
                        <h4 class="fl-cnt-project-by-content-author"><?php echo $this->project->user->name?></h4>
                        <p class="fl-cnt-project-by-content-author-info"><i class="icon-file"></i> <a href="<?php echo $this->project->user->profileUrl?>" title="<?php echo $this->project->user->name; ?>'s profile">Profile</a>,              <span class="like"><i class="icon-thumbs-up"></i> 
                         <?php
                         // like dislike solution 
                         if(!$this->project->isFollower($this->loggedMember)) {
						 ?> <a href="" title="" class="like-member" id="<?php echo $this->project->id;?>" >Like</a>
						 <?php } else { ?>
                            <a href="" title="" class="like-member" id="<?php echo $this->project->id;?>" >Dislike</a>
                         <?php } ?>
                         </span></p>
                        <p class="fl-cnt-project-by-content-author-description"><?php echo $this->project->user->description;?></p>
                        
                        <div class="fl_thin_divider"></div>

<?php 
                if(count ($this->membersProject) > 0){  ?>

                        <div class="fl-cnt-project-by-content-author-projects">
                          <span><a href="/member/profile/my-project/id/<?php echo $this->project->user->id; ?>" title="<?php echo $this->project->user->name; ?>' projects">more of 'My Projects'</a></span>
                        	<ul>                          
							<?php 
									foreach($this->membersProject as $project){ ?>	  		
									<li><a href="/project/index/index/id/<?php echo $project->id ?>" title=""><img src="<?php echo $project->getPictureUrl('tiny'); ?>" alt="<?php echo $project->title?>" title="<?php echo $project->title?>" /></a></li>
								<?php } // end foreach ?>
							</ul> 
                        </div>
<?php }  
if(count ($this->collaborations) > 0){ ?>

                        <div class="fl-cnt-project-by-content-author-projects">
                          <span><a href="/member/profile/my-collaboration/id/<?php echo $this->project->user->id; ?>" title="<?php echo $this->project->user->name; ?>' collaborations">more of 'My Collaborations'</a></span>
							<ul>                          
							<?php 	
									foreach($this->collaborations as $a){
										  		$project = $a->project; // role is for collaborator ?>
									<li><a href="/project/index/index/id/<?php echo $project->id?>" title=""><img src="<?php echo $project->getPictureUrl('tiny'); ?>" alt="<?php echo $project->title?>" title="<?php echo $project->title?>" /></a></li>
								<?php } // end foreach ?>
							</ul>                        
                         
                        </div>
<?php } // end foreach ?>
                      </div>
                    </div>
                  </div>
                </div>
              </div>