<?php if($this->isPoll == false) { echo ""; return; } // check if there are any polls ?>


<?php
// zone for member who has voted
if ($this->hasVoted) { ?>
<h3 class="fl-sidebar-h3">Thank you for your feedback.</h3>
<div class="fl-feedback">

	<ul class="fl-feedback-poll">
	 <?php
	foreach ( $this->answers as $a ) {
		?>
		<li>
			<div class="fl-feedback-question">
				<p><?php echo $a->question->question;?></p>
			</div>
			<div class="fl-feedback-answer text-right">
				<?php echo "<strong>".$a->answer."</strong> (". $a->question->avgOfAnswers().")";?>           
            </div>
		</li>                          
		<?php }?>      
	 </ul>

	<p class="fl-feedback-info">Vote count: <strong><?php echo $this->countOfVotedMembers; ?></strong></p>

</div>

<?php
}
?>
<h3 class="fl-sidebar-h3">Leave feedback - help out!</h3>
<div class="fl_thick_divider"></div>
<div class="fl-feedback">
 				 
<?php echo $this->formPoll;?> 	
</div>
