 <?php if (count($this->paginator) < 1) { return; } // don't display when empty?>
 <h3 class="fl-sidebar-h3">Similar projects</h3>
<?php if (count($this->paginator)) {?>
   
                <div class="fl_thick_divider"></div>
                <div class="fl-similar-projects">
                  <ul class="fl-similar-projects-thumbnails">
                 
   
   
    <?php foreach ($this->paginator as $project){ ?>
        			  <li>
                      <div class="fl-similar">
                        <div class="inner-5">
                          <a href="/project/index/index/id/<?php echo $project->id?>" title="<?php echo $project->title; ?>"><img src="<?php echo $project->getPictureUrl('tiny'); ?>" alt="<?php echo $project->title; ?>" /></a>
                          <h4><?php echo $project->title; ?></h4>

<?php switch($project->level){
  case '1': ?>
                     <div class="fl-level">
                        <div class="progress fl-small-bar">
                          <div class="fl_level1"></div>
                        </div>
                        <div class="progress fl-small-bar">
                          <div class="bar"></div>
                        </div>
                        <div class="progress fl-small-bar">
                          <div class="bar"></div>
                        </div>
                      </div>
<?php ; break;
  case '2': ?>

                      <div class="fl-level">
                        <div class="progress fl-small-bar">
                          <div class="fl_level2"></div>
                        </div>
                        <div class="progress fl-small-bar">
                          <div class="fl_level2"></div>
                        </div>
                        <div class="progress fl-small-bar">
                          <div class="bar"></div>
                        </div>
                      </div>
<?php ; break;
  case '3': ?>

                      <div class="fl-level">
                        <div class="progress fl-small-bar">
                          <div class="fl_level3"></div>
                        </div>
                        <div class="progress fl-small-bar">
                          <div class="fl_level3"></div>
                        </div>
                        <div class="progress fl-small-bar">
                          <div class="fl_level3"></div>
                        </div>
                      </div>
<?php ;
}?>

                        </div>
                      </div>
                    </li>	
    <?php } ?>
  
  
                  </ul>
                </div>				

    <?php } else echo "There are no similar projects "?>
 

                    
                  

             

               