 <h3 class="fl-sidebar">Similar projects</h3>
<?php if (count($this->paginator)) {?>
   
                <div class="fl_thick_divider"></div>
                <div class="fl-similar-projects">
                  <ul class="fl-similar-projects-thumbnails">
                 
   
   
    <?php foreach ($this->paginator as $project){ ?>
        			  <li>
                      <div class="fl-similar">
                        <div class="inner-similar">
                          <a href="/project/index/index/id/<?php echo $project->id?>" title=""><img src="/storage/projects/<?php echo $project->dir."/".$project->getPicture('small'); ?>" alt="" title="" /></a>
                          <h4><?php echo $project->title; ?></h4>
                          <div class="progress fl-similar-project-bar">
                            <div class="fl_level<?php echo $project->level; ?> fl-similar-bar"></div>
                          </div>
                        </div>
                      </div>
                    </li>	
    <?php } ?>
  
  
                  </ul>
                </div>				

    <?php } else echo "There are no similar projects "?>
 

                    
                  

             

               