<?php
		// filtering tasks into 3 levels
		$tasks = array();
		if(count($this->tasks) > 0){
			foreach ( $this->tasks as $t ) {
				$tasks[$t->level][] = $t->toArray();
			}
		}

		$level= 1;
		$content_lvl1 = '<span>Level 1</span>';
		$content_lvl1 .= '<div class="fl_thin_divider"></div>';
		$content_lvl1 .= '<div class="fl_tasks">';

		if(isset($tasks[$level])){ // if is something for first level 
			foreach ( $tasks[$level] as $t ) {
				if($t['finished']){ 
				  $content_lvl1 .= '<i class="icon-ok icon-white"></i> '.$t['task']; 
			    }else{
				  $content_lvl1 .= '<i class="icon-minus icon-white"></i> <em>'.$t['task'].'</em>';
			    }
				$content_lvl1 .= '<br />';
			}
		}else {
			$content_lvl1 .= 'No tasks for level '.$level;
		}
		$content_lvl1 .= '</div>';

		$level = 2;
		$content_lvl2 = '<span>Level 2</span>';
		$content_lvl2 .= '<div class="fl_thin_divider"></div>';
		$content_lvl2 .= '<div class="fl_tasks">';
		if(isset($tasks[$level])){ // 
			
		    foreach ( $tasks[$level] as $t ) {
				if($t['finished']){ 
				  $content_lvl2 .= '<i class="icon-ok icon-white"></i> '.$t['task']; 
			    }else{
				  $content_lvl2 .= '<i class="icon-minus icon-white"></i> <em>'.$t['task'].'</em>';
			    }
				$content_lvl2 .= '<br />';				
			}
			
		}else {
				$content_lvl2 .= "No tasks for level ".$level;
		}
		$content_lvl2 .= '</div>';

		$level = 3;
		$content_lvl3 = '<span>Level 3</span>';
		$content_lvl3 .= '<div class="fl_thin_divider"></div>';
		$content_lvl3 .= '<div class="fl_tasks">';
		if(isset($tasks[$level])){ // 
			
			foreach ( $tasks[$level] as $t ) {
				if($t['finished']){ 
				  $content_lvl3 .= '<i class="icon-ok icon-white"></i> '.$t['task']; 
			    }else{
				  $content_lvl3 .= '<i class="icon-minus icon-white"></i> <em>'.$t['task'].'</em>';
			    }
				$content_lvl3 .= '<br />';				
			}
			
		
		}else {
		  $content_lvl3 .=  "No tasks for level ".$level;
		} 
		$content_lvl3 .= '</div>';
		?>

<script type="text/javascript">

$(document).ready(function(){

	var level = $('.fl-level');
	var lvl1 = $(level).find('.lvl1');
	var lvl2 = $(level).find('.lvl2');
	var lvl3 = $(level).find('.lvl3');

	var position_lvl1 = ["0", "25"];
	var position_lvl2 = ["-117", "25"];
	var position_lvl3 = ["-235", "25"];	

	var content_lvl1 = '<?php echo $content_lvl1; ?>';
	var content_lvl2 = '<?php echo $content_lvl2; ?>';
	var content_lvl3 = '<?php echo $content_lvl3; ?>';


    $(lvl1).simpletip({
    	baseClass: 'fl-simpletip-tooltip',
    	activeClass: 'fl-simpletip-tooltip-lvl1',
    	position: position_lvl1,
        content: content_lvl1,
        hideEffect: 'none',
    });

    $(lvl2).simpletip({
    	baseClass: 'fl-simpletip-tooltip',
    	activeClass: 'fl-simpletip-tooltip-lvl2',
    	position: position_lvl2,
        content: content_lvl2,
        hideEffect: 'none',
    });

    $(lvl3).simpletip({
    	baseClass: 'fl-simpletip-tooltip',
    	activeClass: 'fl-simpletip-tooltip-lvl3',
    	position: position_lvl3,
        content: content_lvl3,
        hideEffect: 'none',
    });



});
</script>
