<div class="fl-form-enter-container">
  <h2>Sign up for FLO~</h2>
  <div class="fl-form-enter">
     <?php echo $this->form; ?>


<div class="control-group">
	<label>Select green square:</label>
	<div class="controls">
		<ul class="fl-human-verification">
			<li class="verification-0">
				<input type="radio" id="verification-0"/>
				<label>Blue</label>
			</li>
			<li class="verification-1">
				<input type="radio" id="verification-1"/>
				<label>Green</label>
			</li>
			<li class="verification-2">
				<input type="radio" id="verification-2"/>
				<label>Red</label>
			</li>
			<li class="verification-3">
				<input type="radio" id="verification-3"/>
				<label>Yellow</label>
			</li>
			<li class="verification-4">
				<input type="radio" id="verification-4"/>
				<label>Black</label>
			</li>
		</ul>
	</div>
</div>





  </div>
  <div class="fl-links">
    <a href="/member/index/log-in" title="Do you want to log in?" class="right">Do you want to log in?</a>
  </div>
</div>
