<!DOCTYPE HTML>

<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>Project-F Beta / <?= (!is_null($this->pageTitle)) ? $this->pageTitle : " Default "; ?> </title>
  <meta name="description" content="">
  <meta name="author" content="Slepice">
  <link rel="shortcut icon" href="/media/slepice-site/1.0.0/img/favicon.ico" />

  <meta name="viewport" content="width=device-width,initial-scale=1">
  <link rel="stylesheet" href="<?=$this->baseUrl('/media/data-tables-1.9.1/css/data-table-bootstrap2-additional.css')?>">
  <?= $this->action('lib', 'index', 'site');  // libraries ?>

   <link rel="stylesheet" href="<?=$this->baseUrl('/media/slepice-site/1.0.0/css/flow_css.css')?>"> 
 </head>

<body>

  <div id="fl-top">
   <div id="fl-container">
    <p>What is FLO~? How does it work? <i class="icon-share-alt"></i> <a href="/index/learn-more" title="Learn more about FLO~">Learn more!</a></p>
   </div>
 </div>

<div id="fl-container">
  <?= $this->action('menu-debug', 'menu', 'project');  ?>
   <div class="container">
     <?= $this->action('header', 'index', 'site');  ?>
   </div>
 	
  <div id="fl-content">
    <div class="container"> 
  		 <?= $this->action('breadcrumbs', 'index', 'site');  ?>

    <div id="container-83-3">
      <div id="container-83-8">
       <div id="col-8">
        <!-- Bootstrap messaging generator -->
        <?php echo $this->flashMessenger() ; ?>
        <?php echo $this->layout()->content; ?>
       </div>
       
       <div id="col-3">
    		<?php echo  $this->action('admin-menu', 'index', 'admin');  ?>
       </div>
     </div>
   </div>

   </div>
   
   <div id="bottom">
        <?= $this->action('footer', 'index', 'site');  ?>
   </div>

</div>

<div id="fl-bottom-line">
  <?= $this->action('footer2', 'index', 'site');  ?>
</div>

</div>




    </body>
</html>
