<?php
$this->step = 1;
echo $this->partial('/index/project-navigation.phtml',array("step" => $this->step,"project" => $this->project,"isCreator"=> $this->isCreator,"isLogged"=> $this->isLogged));
?>    
  </div>
    </div>
    <div id="container-74-4">
      <div id="container-74-7">
        <div id="col-7">         
            <div class="fl-cnt-img">
                <img alt="<?php echo $this->project->title; ?> - main picture" src="<?php echo $this->project->getPictureUrl('large'); ?>" />
            </div>
              <div class="fl-cnt-pitch">
                <p><?php echo $this->project->pitchSentence;?></p>
              </div>

              <div class="fl-cnt-description">
                <?php echo $this->project->content;?>
              </div>

              <div class="fl-cnt-plans-issues-lessons">
               <?php 
                $subContents = $this->project->subContents;
                $first = true;
               	foreach($subContents as $sc){
					?>
					<p>
					<span class="fl-cnt-plans-title<?php if($first) echo "-first";?>"><?php echo $sc->title; ?></span>
					<?php echo $sc->content; ?>
					</p>
				<?php $first = false;}?>
              </div>
    			  <div class="fl-cnt-100 fl-bottom20">
                    <p><?php 
          				// displaying of tags for this project
          				$tags = $this->project->getTagsArray();
          				foreach($tags as $tag){
          					echo $tag;
          				}
          			  ?></p>
            </div>
    				<!-- Author Widget -->
    				<?php echo $this->action('author', 'widget', 'project',array("id" => $this->project->id));?>
        </div>

 