<h2><?php echo $this->project->title?></h2>
              <p class="fl_project_head_info"><i class="icon-user"></i> <a href="<?php echo $this->project->user->getProfileUrl();?>" title=""><?php echo $this->project->user->name?></a>, <i class="icon-folder-close"></i> <?php echo $this->project->category->name;?>, <i class="icon-time"></i> <?php echo $this->project->created->format('Y/m/d');?>,  
                 <span class="like"><i class="icon-thumbs-up"></i> 
                         <?php
                         // like dislike solution 
                         if(!$this->project->isFollower($this->loggedMember)) {
						 ?> <a href="" title="" class="like-project" id="<?php echo $this->project->id;?>" >Like</a>
						 <?php } else { ?>
                            <a href="" title="" class="like-project" id="<?php echo $this->project->id;?>" >Dislike</a>
                         <?php } ?>
                         </span>
              </p>

              
<?php
// basic project navigation
$this->step = 6;
echo $this->partial('/index/project-navigation.phtml',array("step" => $this->step,"project" => $this->project,"isCreator"=> $this->isCreator));
?>
      </div>
    </div>

    <div id="container-74-4">
      <div id="container-74-7">
        <div id="col-7">
<h2>Project board</h2>

<div class="fl-cnt-100">
<?php echo $this->form;?>
</div>

<script>
$(function(){
   var file0 = $("#file_0").closest("div").parent();
   var file1 = $("#file_1").closest("div").parent();
   var file2 = $("#file_2").closest("div").parent();
   var file3 = $("#file_3").closest("div").parent();
   var file4 = $("#file_4").closest("div").parent();
   file1.hide();
   file2.hide();
   file3.hide();
   file4.hide();
   
   $("#file_0").change(function(){if ($("#file_0").val() != ""){file1.show();}});
   $("#file_1").change(function(){if ($("#file_1").val() != ""){file2.show();}});
   $("#file_2").change(function(){if ($("#file_2").val() != ""){file3.show();}});
   $("#file_3").change(function(){if ($("#file_3").val() != ""){file4.show();}});   
});
</script>


<div class="fl-cnt-100">

<?php echo $this->paginationControl($this->paginator, 'Elastic', 'partials/pagination-control-bootstrap.phtml'); ?> 
    <?php if (count($this->paginator) > 0) {?>
    <div class="fl-project-project-board-messages">
    	<?php foreach ($this->paginator as $comment){ ?>


    			 <div class="fl-project-project-board-message">
                   <div class="fl-project-project-board-message-left">
                     <div class="inner">
                       <img src="/storage/users/<?php echo $comment->user->getProfilePicture(100) ; ?>" alt="<?php echo $comment->user->name; ?>' profile picture" />
                     </div>
                   </div>
                   <div class="fl-project-project-board-message-right">
                     <div class="inner">
                       <h3 class="fl-project-project-board-h3"><?php echo $comment->title; ?></h3>
                       <p class="fl-project-project-board-message-header"><i class="icon-user"></i> <?php echo $comment->user->name; ?>, <i class="icon-time"></i> <?php echo $comment->created->format('d-m-y'); ?></p>
                       <p><?php echo $comment->content; ?></p>

                       <?php if(count($comment->files) > 0){?>
						<div class="fl-cnt-100">
						  <div class="alert alert-info">	
							<?php 
						// display children
						foreach($comment->files as $file){ ?>		
						   
							<a href="/project/index/project-board/download/id/<?php echo $project->id;?>/file_id/<?php echo $file->id ;?>">
							<?php echo $file->name ;?> </a>
							<em>{<?php echo $file->getSizeFormat(); ?>,	<?php echo $file->type ; ?>}</em>
							
						<?php }?>
						  </div>
						</div>
						<?php }?>

                     </div>
                   </div>
                 </div>
    	
    	<?php } ?>
    </div>
<?php } else {
	echo "No Comments for this project";
} ?>

  </div>

</div>
