 <?php if($this->project->ban){?>
    <div class="alert alert-danger">
    <strong>Warning!</strong> This project is banned.
    </div>				
<?php } ?>

<h2><?php echo $this->project->title?></h2>
              <p class="fl_project_head_info"><i class="icon-user"></i> <a href="<?php echo $this->project->user->getProfileUrl();?>" title=""><?php echo $this->project->user->name?></a>, <i class="icon-folder-close"></i> <?php echo $this->project->category->name;?>, <i class="icon-time"></i> <?php echo $this->project->created->format('Y/m/d');?>,  
                 <?php if($this->isLogged){?>
                 <span class="like"><i class="icon-thumbs-up"></i> 
                         <?php
                         // like dislike solution 
                         if(!$this->project->isFollower($this->loggedMember)) {
						 ?> <a href="" title="" class="like-project" id="<?php echo $this->project->id;?>" >Like</a>
						 <?php } else { ?>
                            <a href="" title="" class="like-project" id="<?php echo $this->project->id;?>" >Dislike</a>
                         <?php } ?>
                  </span>
                  <?php }?>
   </p>
              

 <?php  
	$allow[1] = false;
	$allow[2] = false;
	$allow[3] = false;
	$allow[4] = false;
	$allow[5] = false;
	$allow[6] = false;
	
	switch ($this->step){
		case 1 : $allow[1] = true;
		break;
		case 2 : $allow[2] = true;
		break;
		case 3 : $allow[3] = true;
		break;
		case 4 : $allow[4] = true;
		break;
		case 5 : $allow[5] = true;
		break;
		case 6 : $allow[6] = true;
		break;
	}	
  ?>
<div class="navbar fl-project-profile-navbar">
                <div class="navbar-inner">
                  <div class="container">
  <ul class="nav">
  <li class="<?php echo($allow[1] == true ? "active" : "disable" );?>"> <a href="<?php echo $this->project->getProjectUrl();?>">Summary</a></li>
  <li class="<?php echo($allow[2] == true ? "active" : "disable" );?>"><a href="<?php echo $this->project->getProjectUrl();?>/updates">Updates</a></li>
  <li class="<?php echo($allow[3] == true ? "active" : "disable" );?>"><a href="<?php echo $this->project->getProjectUrl();?>/comments">Comments</a></li>
  <li class="<?php echo($allow[4] == true ? "active" : "disable" );?>"><a href="<?php echo $this->project->getProjectUrl();?>/survey">Project Survey</a></li>
  <li class="<?php echo($allow[5] == true ? "active" : "disable" );?>"><a href="<?php echo $this->project->getProjectUrl();?>/collaboration">Collaboration</a></li>
 <?php if($this->isCreator){?>
 <li class="<?php echo($allow[6] == true ? "active" : "disable" );?>"><a href="<?php echo $this->project->getProjectUrl();?>/project-board">Project Board</a></li>
  <?php }?>

  <?php 
  	
      if($this->isCreator){
 ?>
  
  	<li><a href="/member/my-project/edit-project/id/<?php echo $this->project->id; ?>" class="right" title=""><i class="icon-wrench icon-white"></i> Edit project as a Creator</a></li>
  </ul>
 <?php     
      } 
   ?>
 
  </div>
                </div>
              </div>