<?php
// basic project navigation
$this->step = 4;
echo $this->partial('/index/project-navigation.phtml',array("step" => $this->step,"project" => $this->project,"isCreator"=> $this->isCreator,"isLogged"=> $this->isLogged));

?>
      </div>
    </div>

    <div id="container-74-4">
      <div id="container-74-7">
        <div id="col-7">
<h2 class="fl-bottom20">Project survey</h2>
                <div class="fl-cnt-100 left text-center">
                  <span class="fl-survey-legend-answered">answered question</span>
                  <span class="fl-survey-legend-unanswered">unanswered question</span>
                  <span class="fl-survey-legend-note">* clicking on a question you will see an answer</span>
                </div>

                <div class="fl_thin_divider"></div>

<div class="fl-cnt-100">
  <?php echo $this->paginationControl($this->paginator, 'All', 'partials/pagination-control-bootstrap.phtml'); ?> 
</div>

    <?php if (count($this->paginator) > 0) {?>
<div class="fl-cnt-100">
  <ul class="fl-project-survey-list">
    	<?php foreach ($this->paginator as $answer){ ?>

<?php if($answer->answer == ""){?>
          <li class="unanswered">
<?php } else {?>
          <li class="answered" onclick="$('#show-<?php echo $answer->question->id;?>').toggle('fast');" id="<?php echo $answer->question->id;?>">
<?php }?>
            <p class="fl-survey-list-question"><?php echo $answer->question->id;?>. <?php echo $answer->question->question;?></p>
            <div class="hide"<?php echo ($answer->answer == "") ? '' : ' id="show-'.$answer->question->id.'"'?>>
              <p class="well"><?php echo $answer->answer;?></p>
            </div>
          </li>
    	<?php } ?>
  </ul>
</div>

<?php 	}
 	else {
	echo "No survey for this project";
} ?>

</div>
