<h2><?php echo $this->project->title?></h2>
              <p class="fl_project_head_info"><i class="icon-user"></i> <a href="<?php echo $this->project->user->getProfileUrl();?>" title=""><?php echo $this->project->user->name?></a>, <i class="icon-folder-close"></i> <?php echo $this->project->category->name;?>, <i class="icon-time"></i> <?php echo $this->project->created->format('Y/m/d');?>,  
                 <span class="like"><i class="icon-thumbs-up"></i> 
                         <?php
                         // like dislike solution 
                         if(!$this->project->isFollower($this->loggedMember)) {
						 ?> <a href="" title="" class="like-project" id="<?php echo $this->project->id;?>" >Like</a>
						 <?php } else { ?>
                            <a href="" title="" class="like-project" id="<?php echo $this->project->id;?>" >Dislike</a>
                         <?php } ?>
                         </span>
              </p>

              
<?php
// basic project navigation
$this->step = 5;
echo $this->partial('/index/project-navigation.phtml',array("step" => $this->step,"project" => $this->project,"isCreator"=> $this->isCreator));
?>

<div class="row">
            <div class="span7">      

<h2>Team</h2>
<div class="fl-cnt-100">
	 <?php if($this->isCollaborator){ ?>
    	<!-- POKUD PRIHLASENEJ UZIVATEL KOUKA DO TETO ZALOZKY A JE V TEAMU, TAK SE ZOBRAZI TADY -->
                <div class="fl-team-logged-user">
                  <div class="inner">
                    <div class="fl-team-logged-user-left">
                 
                    <a href="<?php echo $this->yourRole->user->getProfileUrl();?>"><img src="/storage/users/<?php echo $this->yourRole->user->getProfilePicture(50)?>" alt="<?php echo $this->yourRole->user->getName(); ?>" class="fl-img-list" /></a>
             
                      <span class="fl-team-logged-user-name"><?php echo $this->yourRole->user->name;?></span><br />
                      <span class="fl-team-logged-user-since">~ team member since <?php echo $this->yourRole->created->format("d/m/Y");?></span>
                    </div>
                    <div class="fl-team-logged-user-right">
                      <div class="fl-skill">
                        <div class="fl-skill-img40">
                          <img src="/media/slepice-site/1.0.0/img/role_<?php echo $this->yourRole->name;?>.png" alt="<?php echo $this->yourRole->name;?> role icon"/>
                        </div>
                        <div class="fl-skill-text">
                          <div class="fl-skill-text-roledescription40">
                            <strong><?php echo $this->yourRole->name;?> ~</strong> <?php echo $this->yourRole->description;?>
                          </div>
                        </div>
                      </div>

                    </div>
                  </div>
                </div>
                <div class="fl_thin_divider"></div>
    	<?php }  ?>
	 
                <!-- TEAM -->
                <div class="fl-project-team">
                  
                  <!-- ROLE -->
                  <div class="fl-project-team-role">
                    
                    <?php foreach($this->paginator as $role){?>
                    <!-- USER -->
                    <div class="fl-project-team-role-user">
                      <div class="fl-project-team-role-user-left">
                        <a href="<?php echo $role->user->getProfileUrl();?>"><img src="/storage/users/<?php echo $role->user->getProfilePicture(50)?>" alt="<?php echo $role->user->getName(); ?>" class="fl-img-list" /></a>
          
                        <h4><?php echo $role->user->name; ?></h4>
                        <p><i class="icon-file"></i> <a href="<?php echo $role->user->getProfileUrl();?>">Profile</a></p>
                      </div>
                      <div class="fl-project-team-role-user-right">
                        <div class="fl-skill">
                          <div class="fl-skill-img30">
                            <img src="/media/slepice-site/1.0.0/img/role_<?php echo $role->name; ?>.png" alt="<?php echo $role->name; ?> role icon" />
                          </div>
                          <div class="fl-skill-text">
                            <div class="fl-skill-text-roledescription30">
                              <strong><?php echo $role->name; ?> ~</strong> <?php echo $role->description; ?>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <!-- / USER -->
					<?php }?>
                

                  </div>
                  <!-- / ROLE -->

                  <div class="fl_thin_divider"></div>

                </div>
                <!-- / TEAM -->

</div>
</div>


                