<?php
// basic project navigation
$this->step = 2;
echo $this->partial('/index/project-navigation.phtml',array("step" => $this->step,"project" => $this->project,"isCreator"=> $this->isCreator,"isLogged"=> $this->isLogged));
?>
      </div>
    </div>

    <div id="container-74-4">
      <div id="container-74-7">
        <div id="col-7">
          
<h2 class="fl-bottom20">Updates</h2>

<div class="fl-cnt-100">
<?php echo $this->paginationControl($this->paginator, 'Elastic', 'partials/pagination-control-bootstrap.phtml'); ?> 
</div>

<?php 
    $i = 0;
    if (count($this->paginator) > 0) {

      $i = $this->paginator->getTotalItemCount() - ($this->paginator->getItemCountPerPage() * ($this->paginator->getCurrentPageNumber() - 1)); ?>

<div class="fl-cnt-100">
    	<?php foreach ($this->paginator as $update){ ?>
              <div class="fl-project-update">
                <h3><span class="fl-project-update-h3-prefix">update</span> <span class="fl-project-update-h3-prefix-num">#<?php echo $i; ?></span> <?php echo $update->title;?></h3>
                <div class="fl-cnt-100 fl-top10">
                  <p><span class="fl-project-update-info"><i class="icon-time"></i> <?php echo $update->created->format('d-m-y') ;?></span> ~ <?php echo $update->content;?></p>
                </div>
                <div class="fl_thin_divider"></div>
              </div>

    	<?php $i--; } ?>
</div>
<?php	} else {
	echo "No Updates for this project";
} ?>

</div>
