<div id="container-74-4">
      <div id="container-74-7">
        <div id="col-7"> 
	
<h2>Welcome back, <?php echo $this->member['name']?></h2>
<!-- <p>Your last visit was on <strong>20th of July 2012</strong></p> -->

              <div class="fl-cnt-100">
                <ul class="fl-dashboard">
                  <li><a href="/member/project/create-project-step-one" title=""><i class="fl-dashboard-icon-new"></i> Start new project</a></li>
                  <li><a href="/member/flobox/index" title=""><i class="fl-dashboard-icon-flobox"></i> FLO~ box</a></li>
                  <li><a href="/member/my-project" title=""><i class="fl-dashboard-icon-myprojects"></i> My projects</a></li>
                  <li><a href="/member/my-collaboration" title=""><i class="fl-dashboard-icon-mycollaborations"></i> My collaborations</a></li>
                  <li><a href="/member/my-favourite/project" title=""><i class="fl-dashboard-icon-projectsilike"></i> Projects I like</a></li>
                  <li><a href="/member/my-favourite/member" title=""><i class="fl-dashboard-icon-peopleilike"></i> People I like</a></li>
                </ul>
              </div>

              <div class="fl-cnt-100">
              
              <!-- Recent projects widget -->
   				<?php echo $this->action('recent-project', 'widget', 'member');?>
              
               <!-- Feature projects widget -->
   				<?php echo $this->action('feature-project', 'widget', 'member');?>
         
             </div> 


  </div>

  <div id="col-4">
    <div class="inner">
				<!-- Notification widget -->
   				<?php echo $this->action('notification', 'widget', 'member');?>
          		<!-- Survey widget -->
   				<?php echo $this->action('survey', 'widget', 'member');?>
    </div>
  </div>
  
</div>
</div>


