<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120828204841 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE project DROP FOREIGN KEY FK_2FB3D0EE12469DE2");
        $this->addSql("CREATE TABLE project_category (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("DROP TABLE category");
        $this->addSql("DROP TABLE quote");
        $this->addSql("DROP TABLE user_flo_box_message");
        $this->addSql("ALTER TABLE user CHANGE country country CHAR(2)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE project DROP FOREIGN KEY FK_2FB3D0EE12469DE2");
        $this->addSql("CREATE TABLE category (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE quote (id INT AUTO_INCREMENT NOT NULL, wording VARCHAR(255) NOT NULL, author VARCHAR(255) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE user_flo_box_message (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, type_detail VARCHAR(255) NOT NULL, created DATETIME NOT NULL, message VARCHAR(255) NOT NULL, INDEX IDX_A07735C9A76ED395 (user_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("DROP TABLE project_category");
        $this->addSql("ALTER TABLE user CHANGE country country CHAR(2) DEFAULT NULL");
    }
}
