
<div class="span6">
  <form action="https://www.paypal.com/cgi-bin/webscr" method="post">
  	<fieldset>
  		<legend>Pre-order Offer</legend>
  		<p class="lp-donate">As early adopters interested in taking the chance on our beta, you are already ahead of the curve. Care to get even farther ahead?  Right now we are offering four-month packages of our user-tested, post-beta, soon-to-be-finished application for <strong>$4.99</strong>. This is a limited-time offer while we continue testing things out in beta, smoothing out the rough edges. If you’re really interested in the FLO~ application, now is the time to act in order to lock in savings; we’re well on our way to building something centrally valuable to you, our testers, customers, and the entrepreneurial community as a whole!</p>

    <input type="hidden" name="cmd" value="_s-xclick">
    <input type="hidden" name="hosted_button_id" value="JKWSQSSKGV8TY">
    <input type="submit" name="submit" id="submit" value="Support" class="btn btn-primary right" alt="PayPal - The safer, easier way to pay online!">
    <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
    </fieldset>
  </form>
</div>
<div class="span4">

</div>

