<h2>Newsletters</h2>
              <div class="fl-cnt-100 fl-top20">
                <p><span class="fl-big-number"><?php echo $this->count;?></span> users want to have Newsletter</p>
              </div>

              <div class="fl-cnt-100">
                <div class="fl-nl well">
                  <a href="/admin/newsletter/download" class="btn btn-info"><i class="icon-download-alt icon-white"></i> Save CVS file</a>
                </div>
              </div>
