<?php 
	$this->step = 5;
echo $this->partial('/index/profile-navigation.phtml',array("step" => $this->step,"user" => $this->user,"loggedMember"=> $this->loggedMember));		
			
	?>
<div id="container-74-4">
      <div id="container-74-7">
        <div id="col-7">
	
<h2 class="fl-bottom20">People I like</h2>
<div class="fl-cnt-100">
<?php if (count($this->paginator)) {?>
<?php if (count($this->paginator) > 1 )echo $this->paginationControl($this->paginator, 'Elastic', 'partials/pagination-control-bootstrap.phtml'); ?> 

	
    <?php foreach ($this->paginator as $user){ ?> 
    	<div class="fl-list-user">
                <div class="fl-cnt-20">
                  <div class="fl-user-thumb">
                    <div class="inner-5">
                      <a href="<?php echo $user->getProfileUrl();?>"><img src="<?php echo $user->getProfilePictureUrl("medium")?>" alt="<?php echo $user->getName(); ?>" /> 
                      </a>
                    </div>
                  </div>
                </div>
                <div class="fl-cnt-80">
                  <div class="inner-list-user">
                    <div class="fl-list-user-head">
                      <h3 class="fl-list-user-h3"><?php echo $user->name?> <span>, <i class="icon-file"></i> <a href="<?php echo $user->getProfileUrl();?>" title="<?php echo $user->name?>' profile page">Profile</a></span></h3>
                    </div>
                    <div class="fl-list-user-like">

<?php
		// like dislike solution
		if (! $user->isFriendWithMe ( $this->loggedMember )) {
			?> <a href="" title="" class="like-member-btn btn btn-success" id="<?php echo $user->id;?>"><i class="icon-thumbs-up icon-white"></i>Like</a>
             <?php } else { ?>
				<a href="" title="" class="like-member-btn btn btn-danger" id="<?php echo $user->id;?>"><i class="icon-thumbs-down icon-white"></i>Dislike</a>
             <?php } ?>
                </div>
                    <div class="fl-list-user-projects">
                      <strong>Current projects:</strong><br />
                      <?php 
                      		$projects = $user->projects->slice(0,5); 
                      		$count = count($projects);
                      	
                      		foreach($projects as $project){
                      			$count--;
                      			?>
                      		   <a href="/project/index/index/id/<?php echo $project->id?>" title="<?php echo $project->title; ?>"> 
                 				<?php echo $project->title?></a>
                      			<?php
                      			if($count != 0) echo ","; 
                      		} 	
                      		$projects = null;
                      
                      
                      ?>
                           </div>
                  </div>
                </div>
              </div>
              <div class="fl_thin_divider"></div>


<?php } ?>
</ul>
<?php } else echo "There are members who I like."?>

</div>

</div>	
 <script src="<?=$this->baseUrl('/media/slepice-site/1.0.0/js/like-button-member-project-1.0.0.js')?>"></script>
 
 