<h2 class="fl-bottom20">FLO~ Box <a href="/member/flobox/new" title=""><span class="green"><img src="/media/slepice-site/1.0.0/img/icon_new_project.jpg" alt="" title="" /> create new message</span></a></h2>

<div class="fl-cnt-100">
<!-- FloBox Table Ideas -->
<?php echo $this->paginationControl($this->paginator, 'Elastic', 'partials/pagination-control-bootstrap.phtml'); ?> 
    <?php if (count($this->paginator)) {?>
        <table class="table table-striped">
        <thead>
    		<tr>
    			<th>Title</th>
    			<th>Type</th>
    			<th>Type detail</th>
    			<th>Created</th>
    			<th>Comments</th>
    			<th>Actions</th>
    		</tr>
    	</thead>
    <tbody>
    <?php foreach ($this->paginator as $message){ 
        switch($message->type){
            case 'problem': $label = 'label-important'; break;
            case 'interest': $label = 'label-warning'; break;
            case 'choice': $label = 'label-info'; break;
        }
    ?>
    	<tr>
    	<td><?php echo $message->title; ?></td>
    	<td><span class="label <?php echo $label; ?>"><?php echo $message->type; ?></span></td>
		<td style="width: 180px"><?php echo $message->typeDetail; ?></td>
		<td><?php echo $message->created->format('Y/m/d'); ?></td>		
    	<td><?php echo count($message->comments) ?></td>		
    	<td>
    		<a class="btn btn-info" href="/member/profile/flobox-detail/member_id/<?php echo $this->member['id']?>/message_id/<?php echo $message->id ?>"><i class="icon-file icon-white"></i> Detail</a>
    		<a class="btn btn-danger" href="/member/profile/flobox/message-delete/message_id/<?php echo $message->id ?>"> <i class="icon-remove icon-white"></i> Delete</a>
    	</td>			
    	</tr>	 		
    <?php } ?>
    </tbody>
    </table>
    	
    		
    <?php 
    } else {
        echo "No FloBox Messages.";
    }?>

</div>