<h2 class="fl-bottom20">Ideas Sandbox <a href="/member/flobox/new" title=""><span class="green"><img src="/media/slepice-site/1.0.0/img/icon_new_project.jpg" alt="" title="" /> Create New Idea Message</span></a></h2>

<div class="fl-cnt-100">
  <div class="alert alert-info">
    <p>This is meant as a playground for truly undeveloped ideas. Think of this as Level 0 to the project-page setup’s Level 1. Post short posts about problems you’d like to see solved, solutions to problems that could be interesting ideas to turn into projects. These posts function as “idea statuses” that are visible to all members you follow within FLO~. These users can also leave comments on your posts, serving as potentially the first stage of later collaboration.</p>
  </div>
</div>

<div class="fl-cnt-100">
<!-- FloBox Table Ideas -->
    <?php if (count($this->paginator)) {?>
	<?php if (count($this->paginator) > 1 )echo $this->paginationControl($this->paginator, 'Elastic', 'partials/pagination-control-bootstrap.phtml'); ?> 
    
    <table class="table table-striped">
        <thead>
    		<tr>
    			<th>Title</th>
    			<th>Type</th>
    			<th>Type detail</th>
    			<th>Created</th>
    			<th>Comments</th>
    			<th>Actions</th>
    		</tr>
    	</thead>
    <tbody>
    <?php foreach ($this->paginator as $message){ 
        switch($message->type){
            case 'problem': $label = 'label-important'; break;
            case 'interest': $label = 'label-warning'; break;
            case 'choice': $label = 'label-info'; break;
        }
    ?>
    	<tr>
    	<td><?php echo $message->title; ?></td>
    	<td><span class="label <?php echo $label; ?>"><?php echo $message->type; ?></span></td>
		<td style="width: 180px"><?php echo $message->typeDetail; ?></td>
		<td><?php echo $message->created->format('Y/m/d'); ?></td>		
    	<td><?php echo count($message->comments) ?></td>		
    	<td>
          <div class="input-append input-prepend">
    		<a class="btn btn-info" href="/member/profile/flobox-detail/id/<?php echo $this->member['id']?>/message_id/<?php echo $message->id ?>"><i class="icon-list icon-white"></i> Detail</a><a class="btn btn-danger" href="/member/profile/flobox/message-delete/message_id/<?php echo $message->id ?>"> <i class="icon-remove icon-white"></i> Delete</a>
          </div>
    	</td>			
    	</tr>	 		
    <?php } ?>
    </tbody>
    </table>
    	
    		
    <?php 
    } else {
        echo "No Messages.";
    }?>

</div>