<div class="fl-cnt-100 fl-bottom20">

 
 <!-- Project Displaying -->
<?php if (count($this->paginator)) {?>
<h3 class="fl-uppercase fl-top30">Featured projects</h3>
<div class="fl_thick_divider"></div>    
                <ul class="fl-ul-list-style-none fl-member-projects">
                 <?php foreach ($this->paginator as $project){ ?>
        <li>
                      <div class="fl-member-project">
                        <div class="inner-similar">
                         <a href="/project/index/index/id/<?php echo $project->id?>" title="Public profile page"><img src="<?php echo $project->getPictureUrl('tiny'); ?>" alt="Project picture" /></a>	
       					 <div class="fl-level">                        
						<?php 
						// Display Current Level
						$array[1] = array('fl_level1','bar','bar');
						$array[2] = array('fl_level2','fl_level2','bar');
						$array[3] = array('fl_level3','fl_level3','fl_level3');
						foreach($array[$project->level] as $c){ ?>
						                    <div class="progress fl-small-bar">
						                          <div class="<?php echo $c?>"></div>
						                    </div>
						<?php } ?>
						</div>                  
                          <h4><?php echo $project->title;?></h4>
                          <p class="fl-thumb-p"><i class="icon-user"></i> <a href="/member/profile/index/id/<?php echo $project->user->id;?>" title="<?php echo $project->user->name;?>'s profile"><?php echo $project->user->name;?></a></p>
                          
                        </div>
                      </div>
                    </li>
    <?php }?>
     			</ul>

  <?php } else echo "";?>     
  </div>                              