<div class="fl-cnt-100 fl-bottom20">
<h3 class="fl-uppercase fl-top30">Featured projects</h3>
<div class="fl_thick_divider"></div>  
 
 <!-- Project Displaying -->
<?php if (count($this->paginator)) {?>
             <div class="fl_thick_divider"></div> 
                <ul class="fl-ul-list-style-none fl-member-projects">
                 <?php foreach ($this->paginator as $project){ ?>
        <li>
                      <div class="fl-member-project">
                        <div class="inner-similar">
                         <a href="/project/index/index/id/<?php echo $project->id?>" title="Public profile page"><img src="/storage/projects/<?php echo $project->dir?>/<?php echo $project->getPicture("small");?>" alt="Project picture" /></a>	
       					 <div class="fl-level">                        
						<?php 
						// Display Current Level
						$array[1] = array('fl_level1','bar','bar');
						$array[2] = array('fl_level2','fl_level2','bar');
						$array[3] = array('fl_level3','fl_level3','fl_level3');
						foreach($array[$project->level] as $c){ ?>
						                    <div class="progress fl-small-bar">
						                          <div class="<?php echo $c?>"></div>
						                    </div>
						<?php } ?>
						</div>                  
                          <h4><?php echo $project->title;?></h4>
                          <p class="fl-thumb-p"><i class="icon-user"></i> <?php echo $project->user->name;?></p>
                          
                        </div>
                      </div>
                    </li>
    <?php }?>
     			</ul>

  <?php } else echo "No feature projects.";?>     
  </div>                    
                
<!--                 <div class="btn-group fl-how-many"> -->
<!--                   <a class="btn" href="#">4</a> -->
<!--                   <a class="btn dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a> -->
<!--                   <ul class="dropdown-menu fl-dropdown-menu-numbers"> -->
<!--                       <li><a href="#">4</a></li> -->
<!--                       <li><a href="#">8</a></li> -->
<!--                       <li><a href="#">12</a></li> -->
<!--                       <li><a href="#">16</a></li> -->
<!--                   </ul> -->
<!--                 </div> -->
<!--               </div> -->
          