<?php  
	$allow[1] = false;
	$allow[2] = false;
	$allow[3] = false;
	$allow[4] = false;
	$allow[5] = false;
	$allow[6] = false;
	$allow[7] = false;

	// select active controller
	$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
	$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
	
	switch ($controller){
		case 'project' : $allow[1] = true;
		break;
		case 'my-project' : $allow[2] = true;
		break;
		case 'my-collaboration' : $allow[3] = true;
		break;
		case 'flobox' : $allow[4] = true;
		break;
		case 'my-favourite' :   if($action=="project") $allow[5] = true;
							    if($action=="member") $allow[6] = true; 
								break;
		case 'profile-setting' : $allow[7] = true;
		break;
	}	
  ?>

                <div class="tabs-right">
                  <ul class="nav nav-tabs fl-right-nav">
                   <li><a href="/member/dashboard" title="">Dashboard</a></li>
                   <li class="<?php echo($allow[1] == true ? "active" : "disable" );?>"> <a href="/member/project/create-project-step-one" title="">Start new project</a></li>
                   <li class="<?php echo($allow[2] == true ? "active" : "disable" );?>"> <a href="/member/my-project" title="">Published Projects <span class="label"><?php echo count($this->loggedMember->projects);?></span></a></li>
                   <li class="<?php echo($allow[3] == true ? "active" : "disable" );?>"> <a href="/member/my-collaboration" title="">My Collaborations <span class="label"><?php echo $this->collaborationsCount;?></span></a></li>
                   <li class="<?php echo($allow[4] == true ? "active" : "disable" );?>"> <a href="/member/flobox/index" title="">FLO~ box</a></li>
                   <li class="<?php echo($allow[5] == true ? "active" : "disable" );?>"> <a href="/member/my-favourite/project" title="">Projects I like <span class="label"><?php echo count($this->loggedMember->favouriteProjects); ?></span></a></li>
                   <li class="<?php echo($allow[6] == true ? "active" : "disable" );?>"> <a href="/member/my-favourite/member" title="">People I like <span class="label"><?php echo count($this->loggedMember->myFriends); ?></span></a></li>
                   <li class="<?php echo($allow[7] == true ? "active" : "disable" );?>"> <a href="/member/profile-setting/member-info">Personal Info &amp; Settings</a></li>
                  </ul>
 </div>
 				