<!-- TODO PREDELAT NA GENEROVANY MENU -->
                <div class="tabs-right">
                  <ul class="nav nav-tabs fl-right-nav">
                    <li><a href="/member/project/create-project-step-one" title="">Start new project</a></li>
                    <li><a href="/member/my-project" title="">My projects <span class="label">3</span></a></li>
                    <li><a href="/member/my-collaboration" title="">My collaborations <span class="label"><?php echo $this->collaborationsCount;?></span></a></li>
                    <li><a href="/member/flobox/index" title="">FLO~ box</a></li>
                    <li><a href="/member/my-favourite/project" title="">Projects I like <span class="label"><?php echo count($this->loggedMember->favouriteProjects); ?></span></a></li>
                    <li><a href="/member/my-favourite/member" title="">People I like <span class="label"><?php echo count($this->loggedMember->myFriends); ?></span></a></li>
                    <li><a href="/member/profile-setting/member-info">Personal info</a></li>
                  </ul>
 				</div>
 				