<div class="fl-cnt-100">
<!-- Project Displaying -->
<?php if (count($this->paginator)) {?>
<h3 class="fl-uppercase fl-top30">My Recent projects</h3>
<div class="fl_thick_divider"></div>    
                <ul class="fl-ul-list-style-none fl-thumb-projects4">
                 <?php foreach ($this->paginator as $project){ ?>
        <li>
                      <div class="fl-member-project">
                        <div class="inner-similar">
                         <a href="<?php echo $project->getProjectUrl();?>" title="Public profile page"><img src="<?php echo $project->getPictureUrl('tiny'); ?>" alt="Project picture" /></a>	
       					 <div class="fl-level">                        
						<?php 
						// Display Current Level
						$array[1] = array('fl_level1','bar','bar');
						$array[2] = array('fl_level2','fl_level2','bar');
						$array[3] = array('fl_level3','fl_level3','fl_level3');
						foreach($array[$project->level] as $c){ ?>
						                    <div class="progress fl-small-bar">
						                          <div class="<?php echo $c?>"></div>
						                    </div>
						<?php } ?>
						</div>                  
                          <h4><?php echo $project->title;?></h4>
                          
                          

                          <div class="text-center">
                            <div class="input-append input-prepend">
                              <a href="<?php echo $project->getProjectUrl();?>" title="Go to Project profile" class="btn btn-success"><i class="icon-picture icon-white"></i> Profile</a><a href="/member/my-project/edit-project/id/<?php echo $project->id?>" title="Edit this project" class="btn btn-danger"><i class="icon-wrench icon-white"></i> Edit</a>
                            </div>
                          </div>
                          
                        </div>
                      </div>
                    </li>
    <?php }?>
     			</ul>

  <?php } else echo "";?>     
  </div>                              