 
  <h3 class="fl-uppercase fl-top30">Recent projects <span>(people i like)</span></h2>
          
             <div class="fl_thick_divider"></div> 
                <ul class="fl-ul-list-style-none fl-thumb-projects4">

                    <li>
                      <div class="fl-member-project">
                        <div class="inner-similar">
                          <a href="" title=""><img src="slepice/img/project_img_similar.jpg" alt="" title="" /></a>
                          
<?php switch(1){
  case '1': ?>
                     <div class="fl-level">
                        <div class="progress fl-small-bar">
                          <div class="fl_level1"></div>
                        </div>
                        <div class="progress fl-small-bar">
                          <div class="bar"></div>
                        </div>
                        <div class="progress fl-small-bar">
                          <div class="bar"></div>
                        </div>
                      </div>
<?php ; break;
  case '2': ?>

                      <div class="fl-level">
                        <div class="progress fl-small-bar">
                          <div class="fl_level2"></div>
                        </div>
                        <div class="progress fl-small-bar">
                          <div class="fl_level2"></div>
                        </div>
                        <div class="progress fl-small-bar">
                          <div class="bar"></div>
                        </div>
                      </div>
<?php ; break;
  case '3': ?>

                      <div class="fl-level">
                        <div class="progress fl-small-bar">
                          <div class="fl_level3"></div>
                        </div>
                        <div class="progress fl-small-bar">
                          <div class="fl_level3"></div>
                        </div>
                        <div class="progress fl-small-bar">
                          <div class="fl_level3"></div>
                        </div>
                      </div>
<?php ;
}?>

                          <h4>Web for Pub in South Africa</h4>
                          <p class="fl-thumb-p"><i class="icon-user"></i> Name of the author</p>
                          
                        </div>
                      </div>
                    </li>

                </ul>
                
<!--                 <div class="btn-group fl-how-many"> -->
<!--                   <a class="btn" href="#">4</a> -->
<!--                   <a class="btn dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a> -->
<!--                   <ul class="dropdown-menu fl-dropdown-menu-numbers"> -->
<!--                       <li><a href="#">4</a></li> -->
<!--                       <li><a href="#">8</a></li> -->
<!--                       <li><a href="#">12</a></li> -->
<!--                       <li><a href="#">16</a></li> -->
<!--                   </ul> -->
<!--                 </div> -->
<!--               </div> -->
          