<h2 class="fl-bottom20">Projects I like</h2>


<div class="fl-cnt-100">
<!-- Project Displaying -->
<?php if (count($this->paginator)) {?>
<?php if (count($this->paginator) > 1) echo $this->paginationControl($this->paginator, 'Elastic', 'partials/pagination-control-bootstrap.phtml'); ?> 

    <?php foreach ($this->paginator as $project){ ?>

    	       
            <div class="fl-list-project">
                  <div class="fl-cnt-20">
                    <div class="fl-project-thumb">
                      <div class="inner-5">
                        <a href="/project/index/index/id/<?php echo $project->id?>" title="Public profile page"><img src="<?php echo $project->getPictureUrl("small");?>" alt="Project picture" /></a>
                       
                       <div class="fl-level">                        
            <?php 
            // Display Current Level
            $array[1] = array('fl_level1','bar','bar');
            $array[2] = array('fl_level2','fl_level2','bar');
            $array[3] = array('fl_level3','fl_level3','fl_level3');
            foreach($array[$project->level] as $c){ ?>
                                <div class="progress fl-small-bar">
                                      <div class="<?php echo $c?>"></div>
                                </div>
            <?php } ?>
            </div>
                      </div>
                    </div>
                  </div>
                  <div class="fl-cnt-60">
                    <div class="inner-list-project">
                      <div class="fl-cnt-100 fl-bottom10">
                        <h3 class="fl-list-project-h3"><?php echo $project->title?></h3>
                        <p class="fl-list-project-info"><i class="icon-user"></i> Creator, <i class="icon-folder-close"></i> <?php echo $project->category->name?>, <i class="icon-eye-open"></i> <?php echo $project->getCountFollowers();?> Followers</p>
                      </div>
                      <div class="fl-cnt-100 fl-bottom10">
                        <p><?php echo shorter($project->pitchSentence, 100); ?></p>
                      </div>
                      <div class="fl-list-project-roles">
                        <?php 
                       		 $display = false;
                        // if level 1 display all logos   
						if($project->level == 1) {
                        $freePositions = \App\Entity\ProjectRole::getRolesArray();
							$display = true;
						}
						if($project->level == 2){
                       // if level 2 display free positions
                        $facadeProject = new \App\Facade\Project\TeamFacade($this->em);
                    	$freePositions = $facadeProject->findFreeUniqueProjectRolesForProjectArray($project->id); 
							$display =  true;	
						}

            if($project->disableRoleWidget){
               $display = false;
             }
						
						if($display){
						
                    	// if level 3 = have no idea what to display or not
                    	foreach ($freePositions as $r){
                    		
                    		echo '<img src="/media/slepice-site/1.0.0/img/role_'.$r.'.png" alt="'.$r.'" title="'.$r.'" /> ';
                
                    	}
						} 
                    	?>
                      </div>
                    </div>
                  </div>
                  <div class="fl-cnt-20">
                    <a href="/project/index/index/id/<?php echo $project->id?>" class="btn btn-success fl-width80 fl-top5"><i class="icon-picture icon-white"></i> Public profile</a>                   
                    <a href="?_method=like-project&&project_id=<?php echo $project->id;?>" title="" class="btn btn-danger fl-width80 fl-top5"><i class="icon-thumbs-down icon-white"></i> Dislike project</a>  
                  </div>
                </div>
                <div class="fl_thin_divider"></div>

    	
       
    <?php } ?>

    <?php } else echo "You don't like anything!"?>
</div>
     

    
