<?php 
	$this->step = 6;
echo $this->partial('/profile/profile-navigation.phtml',array("step" => $this->step,"user" => $this->user,"loggedMember"=> $this->loggedMember));		
			
?>
<div id="container-74-4">
      <div id="container-74-7">
        <div id="col-7">

<h2 class="fl-bottom20">Projects I like</h2>


<div class="fl-cnt-100">
<!-- Project Displaying -->
<?php if (count($this->paginator) > 1) echo $this->paginationControl($this->paginator, 'Elastic', 'partials/pagination-control-bootstrap.phtml'); ?> 

    <?php if (count($this->paginator)) {?>
	 <?php foreach ($this->paginator as $project){ ?>
              <div class="fl-list-project">
                <div class="fl-cnt-20">
                  <div class="fl-project-thumb">
                    <div class="inner-5">
                      <a href="/project/index/index/id/<?php echo $project->id?>" title="<?php echo $project->title; ?>"> 
                        <img alt="<?php echo $project->title; ?> - main picture" src="<?php echo $project->getPictureUrl("small");?>" />
                     </a>
                                    <div class="fl-level">
                        <?php 
                        // Display Current Level
                        $array[1] = array('fl_level1','bar','bar');
                        $array[2] = array('fl_level2','fl_level2','bar');
                        $array[3] = array('fl_level3','fl_level3','fl_level3');
                        foreach($array[$project->level] as $c){ ?>
                                            <div class="progress fl-small-bar">
                                                  <div class="<?php echo $c?>"></div>
                                            </div>
                        <?php } ?>
                        </div>
                    </div>
                  </div>
                </div>

                <div class="fl-cnt-60">
                  <div class="inner-list-project">
                    <div class="fl-list-project-head">
                      <h3 class="fl-list-project-h3"><?php echo $project->title; ?></h3>
                      <p class="fl-list-project-info"><span class="author"><i class="icon-user"></i> <a href="/member/profile/index/id/<?php echo $project->user->id?>" title="<?php echo $project->user->name?>'s profile"><?php echo $project->user->name?></a></span> <span class="category"><i class="icon-folder-close"></i> <?php echo $project->category->name?></span>
                         <span class="followers"><i class="icon-eye-open"></i> <strong class="follower-count"><?php echo $project->getCountFollowers();?></strong>  followers</span></p>
                    </div>
                    
                    <div class="fl-list-project-roles fl-top20">
                      <?php 
                           $display = false;
                        // if level 1 display all logos   
            if($project->level == 1) {
                        $freePositions = \App\Entity\ProjectRole::getRolesArray();
              $display = true;
            }
            if($project->level == 2){
                       // if level 2 display free positions
                        $facadeProject = new \App\Facade\Project\TeamFacade($this->em);
                      $freePositions = $facadeProject->findFreeUniqueProjectRolesForProjectArray($project->id); 
              $display =  true; 
            }

            if($project->disableRoleWidget){
               $display = false;
             }
            
            if($display){
                      // if level 3 = have no idea what to display or not
                      foreach ($freePositions as $r){ 
                        echo '<img src="/media/slepice-site/1.0.0/img/role_'.$r.'.png" alt="'.$r.'" title="'.$r.'" /> ';
                      }
            	} 
                      ?>
                    </div>
                  </div>
                </div>
                <div class="fl-cnt-20">
                      <?php
                         // like dislike solution 
                         if(!$project->isFollower($this->loggedMember)) {
             ?> <a href="" title="" class="like-project-btn btn btn-success" id="<?php echo $project->id;?>" ><i class="icon-thumbs-up icon-white"></i>Like</a>
             <?php } else { ?>
                            <a href="" title="" class="like-project-btn btn btn-danger" id="<?php echo $project->id;?>" ><i class="icon-thumbs-down icon-white"></i>Dislike</a>
                         <?php } ?>
                    </div>
              </div>
              <div class="fl_thin_divider"></div>




       
    <?php }  } else echo "No Projects Available"?>
 
 </div>
 </div>   
 <script src="<?=$this->baseUrl('/media/slepice-site/1.0.0/js/like-button-member-project-1.0.0.js')?>"></script>
 
 
   
