<?php 
	$this->step = 2;
	echo $this->partial('/profile/profile-navigation.phtml',array("step" => $this->step,"user" => $this->user,"loggedMember"=> $this->loggedMember));		
		
	?>
<div id="container-74-4">
      <div id="container-74-7">
        <div id="col-7">

<h2>FloBox</h2>		

<div class="fl-cnt-100">
<!-- FloBox Table Ideas -->
<?php if (count($this->paginator)) {?>
	<?php if (count($this->paginator) > 1) echo $this->paginationControl($this->paginator, 'Elastic', 'partials/pagination-control-bootstrap.phtml'); ?> 
    
    <?php foreach ($this->paginator as $message){ ?>
    <div class="fl-cnt-100">
    	<?php
    	$typeClass=""; 
    	if($message->type == \App\Entity\UserFloBox::MESSAGE_TYPE_CHOICE) $typeClass = "label-info";
    	if($message->type == \App\Entity\UserFloBox::MESSAGE_TYPE_INTEREST) $typeClass =  "label-warning"; 
      if($message->type == \App\Entity\UserFloBox::MESSAGE_TYPE_PROBLEM) $typeClass =  "label-important";
    	?>

      <h3 class="flobox-title"><span class="label <?php echo $typeClass;?>"><?php echo $message->type; ?></span> <?php echo $message->title; ?> <span class="flobox-title-info"><i class="icon-time"></i> <?php echo $message->created->format('Y/m/d'); ?>, <i class="icon-comment"></i> <?php echo count($message->comments) ?></span></h3>

      <div class="fl-cnt-100 fl-top10">
        <p><?php echo $message->message; ?></p>
      </div>
      <div class="fl-cnt-100 text-right fl-top10">
        <a class="btn btn-info" href="/member/profile/flobox-detail/id/<?php echo $this->member['id']?>/message_id/<?php echo $message->id ?>">Detail</a>
      </div>    
    </div>	
    <div class="fl_thick_divider"></div> 		
    <?php } ?>
  
    	
    		
    <?php } else echo "No FloBox Messages."?>
</div> 
</div> 



    
