 <?php  
	$allow[1] = false;
	$allow[2] = false;
	$allow[3] = false;
	$allow[4] = false;
	$allow[5] = false;
	$allow[6] = false;
	$allow[7] = false;
	$allow[8] = false;
	
	switch ($this->step){
		case 1 : $allow[1] = true;
		break;
		case 2 : $allow[2] = true;
		break;
		case 3 : $allow[3] = true;
		break;
		case 4 : $allow[4] = true;
		break;
		case 5 : $allow[5] = true;
		break;
		case 6 : $allow[6] = true;
		break;
		case 7 : $allow[7] = true;
		break;
		case 8 : $allow[8] = true;
		break;
		case 9 : $allow[9] = true;
		break;
		
	}
  ?>

  <div class="row">
    <div class="span11">
       <?php if($this->user->ban) {?> 
              <div class="alert alert-danger">This User Has Been Banned</div>
              <?php 
              }
        ?>
   			<div class="fl-membeprofile-head">
              <img src="<?php echo $this->user->getProfilePictureUrl("small")?>" alt="<?= $this->member['name'];?>" class="fl-memberprofile-member-img-thumb" />
              <h2><?php echo $this->user->getName(); ?></h2>
              <p class="fl_project_head_info">
                <i class="icon-time"></i> Member since <?php echo $this->user->created->format('d/m/y');?>, <i class="icon-thumbs-up"></i> 
                                      <?php
									// like dislike solution
									if (! $this->user->isFriendWithMe ( $this->loggedMember )) {
										?> <a href="" title="" class="like-member" id="<?php echo $this->user->id;?>">Like</a>
							             <?php } else { ?>
							                            <a href="" title="" class="like-member" id="<?php echo $this->user->id;?>">Dislike</a>
                         <?php } ?>
              </p>
            
            </div>

              <div class="navbar fl-project-profile-navbar">
                <div class="navbar-inner">
                  <div class="container">
                      <ul class="nav">                      
                       <li class="<?php echo($allow[1] == true ? "active" : "disable" );?>"><a href="/member/profile/index/id/<?php echo $this->user->getId(); ?>">Summary</a></li>
                       <li class="<?php echo($allow[2] == true ? "active" : "disable" );?>"><a href="/member/profile/flobox/id/<?php echo $this->user->getId(); ?>">FLO~  Box</a></li>
                        <li class="<?php echo($allow[3] == true ? "active" : "disable" );?>"><a href="/member/profile/my-project/id/<?php echo $this->user->getId(); ?>">Published Projects</a></li>
                        <li class="<?php echo($allow[4] == true ? "active" : "disable" );?>"><a href="/member/profile/my-collaboration/id/<?php echo $this->user->getId(); ?>">My collaborations</a></li>
                        <li class="<?php echo($allow[5] == true ? "active" : "disable" );?>"><a href="/member/profile/favourite-member/id/<?php echo $this->user->getId(); ?>">People I like</a></li>
                       <li class="<?php echo($allow[6] == true ? "active" : "disable" );?>"><a href="/member/profile/favourite-project/id/<?php echo $this->user->getId(); ?>">Projects I like</a></li>
                      </ul>
                  </div>
                </div>
              </div>
          </div>
       </div>