 
                <div class="fl-cnt-100">
                
                <?php 
                foreach($this->user->specificRoles as $r){
                	?>
                	
                	 <div class="fl-skill">
                    <div class="fl-skill-img40">
                      <img src="/media/slepice-site/1.0.0/img/role_<?php echo $r->name;?>.png" alt="<?php echo $r->name;?>" title="<?php echo $r->name;?>" />
                    </div>
                    <div class="fl-skill-text">
                      <div class="fl-skill-text-role">
                       <?php echo $r->name;?>
                      </div>
                      <div class="fl-skill-text-tags">
                       <?php 
                       		foreach($r->tags as $t){
                       			echo $t->name." ";
                       		}
                       ?>
                      </div>
                    </div>
                  </div>
                	

                <?php }  ?>
                 

                  <div class="fl_thin_divider"></div>
                  <div class="fl-skill">
                    <div class="fl-skill-img40">
                      <img src="/media/slepice-site/1.0.0/img/role_earned.png"  title="" />
                    </div>
                   </div>

                </div>