  <h2 class="fl-bottom20">My collaborations</h2>

<?php 
// The main project navigation
$this->step = 1;
echo $this->partial('my-collaboration/my-collaboration-navigation.phtml',array("step" => $this->step));
?>

<div class="fl-cnt-100 fl-top">

<?php 
if(count ($this->applications) > 0){	
	foreach($this->applications as $a){
	  $project = $a->project; // role is for collaborator
?>
                <div class="fl-list-project">
                  <div class="fl-cnt-20">
                    <div class="fl-project-thumb">
                      <div class="inner-5">
                        <a href="/project/index/index/id/<?php echo $project->id;?>" title="Public profile of project <?php echo $project->title?>"><img src="/storage/projects/<?php echo $project->dir?>/<?php echo $project->getPicture("small");?>" alt="Project picture" /></a>
                        <div class="fl-level">
                        <?php 
                        // Display Current Level
                        $array[1] = array('fl_level1','bar','bar');
                        $array[2] = array('fl_level2','fl_level2','bar');
                        $array[3] = array('fl_level3','fl_level3','fl_level3');
                        foreach($array[$project->level] as $c){ ?>
                                            <div class="progress fl-small-bar">
                                                  <div class="<?php echo $c?>"></div>
                                            </div>
                        <?php } ?>
                        </div>
                      
                      </div>
                    </div>
                  </div>
                  <div class="fl-cnt-60">
                    <div class="inner-list-project">
                      <div class="fl-cnt-100">
                        <h3 class="fl-list-project-h3"><?php echo $project->title?></h3>
                        <p class="fl-list-project-info"><i class="icon-folder-close"></i> <?php echo $project->category->name?>, <i class="icon-eye-open"></i> <?php echo $project->getCountFollowers();?> Followers</p>
                      </div>
                      <div class="fl-cnt-100 fl-top40">
                        <div class="fl-list-project-roles-available">
                         <?php 
                       		 $display = false;
                        // if level 1 display all logos   
						if($project->level == 1) {
                        $freePositions = \App\Entity\ProjectRole::getRolesArray();
							$display = true;
						}
						if($project->level == 2){
                       // if level 2 display free positions
                        $facadeProject = new \App\Facade\Project\TeamFacade($this->em);
                    	$freePositions = $facadeProject->findFreeUniqueProjectRolesForProjectArray($project->id); 
							$display =  true;	
						}
						
						if($display){
						
                    	// if level 3 = have no idea what to display or not
                    	foreach ($freePositions as $r){
                    		echo '<img src="/media/slepice-site/1.0.0/img/role_'.$r.'.png" alt="'.$r.'" title="'.$r.'" />';
                    	
                    	}
						} 
                    	?>
                        </div>
                        <div class="fl-list-project-roles-my">
                          <img src="/media/slepice-site/1.0.0/img/role_<?php echo $a->roleName?>.png" alt="Your role is <?php echo $a->roleName?>" title="Your role is <?php echo $a->roleName?>" />
                          
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="fl-cnt-20">
                    <ul class="nav nav-pills nav-stacked fl-collaborations-nav">
                      <li><a href="/project/index/update/id/<?php echo $project->id?>" title="Updates of this project">Updates</a></li>
                      <li><a href="/project/index/project-board/id/<?php echo $project->id?>" title="Project board">Project board</a></li>
                      <li><a href="/project/index/team/id/<?php echo $project->id?>" title="Team of this project">Team</a></li>
                      <li><a href="#surveyModal-id-<?php echo $a->id;?>" title="Project survey" data-toggle="modal">Project survey</a></li>
                      <li><a href="/project/index/comment/id/<?php echo $project->id?>" title="Comments for this project">Comments</a></li>
                    </ul>
                  </div>
                </div>
				
				<!-- modal -->
				<div class="modal hide" id="surveyModal-id-<?php echo $a->id;?>">
					<div class="modal-body">
					     <p><?php echo $a->content;?></p>
					     </div>
					     <div class="modal-footer"> <a href="#" class="btn" data-dismiss="modal">Close</a></div>
					</div>
                <div class="fl_thin_divider"></div>



<?php 
  } // end foreach
}else{
 	echo "No applications";
 } ?>

  </div>




