<h2 class="fl-bottom20">My projects <a href="/member/project/create-project-step-one" title="Start new project"><span class="green"><img src="/media/slepice-site/1.0.0/img/icon_new_project.jpg" alt="start new project icon" /> start new project</span></a></h2>

<div class="fl-cnt-100">
<?php 
if(count ($this->projects) > 0){ 
  foreach($this->projects as $project){
?>
                <div class="fl-list-project">
                  <div class="fl-cnt-20">
                    <div class="fl-project-thumb">
                      <div class="inner-5">
                        <a href="/project/index/index/id/<?php echo $project->id?>" title="Public profile page"><img src="/storage/projects/<?php echo $project->dir?>/<?php echo $project->getPicture("small");?>" alt="Project picture" /></a>

<?php switch($project->level){
  case '1': ?>
                     <div class="fl-level">
                        <div class="progress fl-small-bar">
                          <div class="fl_level1"></div>
                        </div>
                        <div class="progress fl-small-bar">
                          <div class="bar"></div>
                        </div>
                        <div class="progress fl-small-bar">
                          <div class="bar"></div>
                        </div>
                      </div>
<?php ; break;
  case '2': ?>

                      <div class="fl-level">
                        <div class="progress fl-small-bar">
                          <div class="fl_level2"></div>
                        </div>
                        <div class="progress fl-small-bar">
                          <div class="fl_level2"></div>
                        </div>
                        <div class="progress fl-small-bar">
                          <div class="bar"></div>
                        </div>
                      </div>
<?php ; break;
  case '3': ?>

                      <div class="fl-level">
                        <div class="progress fl-small-bar">
                          <div class="fl_level3"></div>
                        </div>
                        <div class="progress fl-small-bar">
                          <div class="fl_level3"></div>
                        </div>
                        <div class="progress fl-small-bar">
                          <div class="fl_level3"></div>
                        </div>
                      </div>
<?php ;
}?>

                      </div>
                    </div>
                  </div>

                  <div class="fl-cnt-60">
                    <div class="inner-list-project">
                      <div class="fl-cnt-100">
                        <h3 class="fl-list-project-h3"><?php echo $project->title?></h3>
                        <p class="fl-list-project-info"><i class="icon-folder-close"></i> <?php echo $project->category->name?>, <i class="icon-eye-open"></i> <?php echo $project->getCountFollowers();?> Followers</p>
                      </div>
                      
                      <div class="fl-cnt-100 fl-list-project-roles fl-top10">
                        <div class="fl-list-project-roles-available">
                        <?php 
		                        // if level 1 display all logos   
								if($project->level == 1)
		                        $freePositions = \App\Entity\ProjectRole::getRolesArray();
		                        
								if($project->level == 2){
		                       // if level 2 display free positions
		                        $facadeProject = new \App\Facade\Project\TeamFacade($this->em);
		                    	$freePositions = $facadeProject->findFreeUniqueProjectRolesForProjectArray($project->id); 
								}
		                    	// if level 3 = have no idea what to display or not
		                    	foreach ($freePositions as $r){
		                    		echo '<img src="/media/slepice-site/1.0.0/img/role_'.$r.'.png" alt="'.$r.'" title="'.$r.'" />';
		                   		} 
                    	?>
                      	<p class="fl-list-project-queue"><strong>
                      	  <?php 
                      	  $facadeProject = new \App\Facade\Project\TeamFacade($this->em);
		                 echo $facadeProject->findApplicationsCount($project->user->id, $project->id,array('state'=>\App\Entity\ProjectApplication::APPLICATION_NEW )); 
		                  ?>
                      	members</strong> are waiting</p>
                        
                        </div>
                        <div class="fl-list-project-roles-my">
                          <?php 
	                 	  foreach($project->getCreatorRolesArray() as $r){
	                 	  	echo  '<img src="/media/slepice-site/1.0.0/img/role_'.$r.'.png" alt="'.$r.'" title="'.$r.'" /> ';
	                 	  }?>
                          </div>
                      </div>
                    </div>
                  </div>
                  <div class="fl-cnt-20">
                    <a href="/member/my-project/edit-project/id/<?php echo $project->id?>" class="btn btn-danger fl-width80"><i class="icon-wrench icon-white"></i> edit project</a>
                    <a href="/project/index/index/id/<?php echo $project->id?>" class="btn btn-success fl-width80 fl-top5"><i class="icon-picture icon-white"></i> public profile</a>                   
                  </div>

                  <div class="fl-cnt-100 fl-margin-top10">
                    <ul class="nav nav-pills fl-projectlist-nav">
                      <li><a href="/member/my-project/update/id/<?php echo $project->id?>" title="Updates of the project">Updates</a></li>
                      <li><a href="/member/my-project/project-board/id/<?php echo $project->id?>" title="Project board of the project">Project board</a></li>
                      <li><a href="/member/my-project/poll/id/<?php echo $project->id?>" title="Polls of the project">Polls</a></li>
                      <li><a href="/member/my-project-team/index/id/<?php echo $project->id?>" title="Team of the project">Team <span class="label label-info">5/13</span></a></li>
                      <li><a href="/member/my-project/survey/id/<?php echo $project->id?>" title="Project sruvey">Project survey <span class="label label-info">10/50</span></a></li>
                      <li><a href="/member/my-project/comment-creator/id/<?php echo $project->id?>" title="Comments for creator of the project">Comments for you <span class="label label-info">10</span></a></li>
                    </ul>
                  </div>
                </div>

                <div class="fl_thin_divider"></div>

<?php	
  } // end foreach
} else {
	
	echo "No projects";
	
}?>

 </div>



