<?php 
$this->step = 9;
echo $this->partial('my-project/my-project-navigation.phtml',array("step" => $this->step,"project" => $this->project));
?>

<h3 class="fl-edit-project-subsection">Create New Poll <a class="btn btn-inverse right" href="/member/my-project/poll/id/<?php echo $this->project->id?>" title="Back to the list of polls"><i class="icon-th-list icon-white"></i> Back to list of Polls</a></h3>

<div class="fl-cnt-100 fl-form-box">
<?php echo $this->form;?>
</div>