<?php 
$this->step = 9;
echo $this->partial('my-project/my-project-navigation.phtml',array("step" => $this->step,"project" => $this->project));
?>

<div class="fl-cnt-100">

<div class="well">
	<a class="btn btn-info" href="/member/my-project/poll/id/<?php echo $this->project->id?>">Back to polls</a>
</div>
</div>



<?php if (count($this->paginator)) {?> 
<div class="fl-cnt-100">
<?php if (count($this->paginator) > 1 )echo $this->paginationControl($this->paginator, 'Elastic', 'partials/pagination-control-bootstrap.phtml'); ?> 

    <?php 
    foreach ($this->paginator as $answer){ ?>
    	<?php 
    	$user = $answer->user;
    	
    	$facadePoll = new \App\Facade\Project\PollFacade($this->em);
    	$answers = $facadePoll->findAllAnswersForUser($this->project->id, $this->loggedMember->id, $answer->poll->id);
    
    	?>
    	<?php echo "User has been voting" . $user->name. " <br>";?>
    	
		<?php 
				foreach ($answers as $a){
					echo $a->question->question . ' odpo '. $a->answer;
					echo "<br>";
				}
		
				echo "<hr>";
		?>
		
		<?php //echo "q ". $o['question']. " answr ". $o['answer'];    	?>	 		
    <?php } ?>
    
</div>    	
    		
    <?php }?>





