<?php 
$this->step = 3;
echo $this->partial('my-project/my-project-navigation.phtml',array("step" => $this->step,"project" => $this->project));
?>

<div class="fl-cnt-100">
  <div class="alert alert-info">
    <p><span class="label label-info">Info</span> Info about unanswered question. Info about unanswered question. Info about unanswered question. Info about unanswered question. Info about unanswered question. <strong>empty answers : <?php echo count($this->emptyAnswers);?></strong></p>
  </div>
</div>

<!-- KONTROLNI VYPIS PRO PEPU -->
<div class="fl-cnt-100">
<div class="well">
<?php 
	foreach ($this->emptyAnswers as $answer){
		$unansweredQuestion[] = $answer->question->id;
		//	pr(array($answer->id,$answer->question->question,$answer->question->id));
	}
 	pr($unansweredQuestion);
?>
</div>
</div>

<div class="fl-cnt-100">
  <div class="well">
	<div id="title-target"></div>
  </div>   
</div>

<div class="fl-cnt-100">
  <?php  echo $this->form;   ?>
</div>

<!-- Load jQuery build -->
<script type="text/javascript" src="<?=$this->baseUrl('/media/jquery.stepy-1.1.0/js/jquery.validate.min.js')?>"></script>
<script type="text/javascript" src="<?=$this->baseUrl('/media/jquery.stepy-1.1.0/js/jquery.stepy.js')?>"></script>
<script type="text/javascript">
$(document).ready(function()
		{	// disable cache
			 $.ajaxSetup ({cache: false });  	
			// $("#submit").hide();
			 $('#step').stepy({
				 next: function(index) {
				    if(index==16){
					   	// $("#submit").show();	
					}
					}
				 ,
				  finishButton:	false,
				  nextLabel:      'Next question',
				  backLabel:      'Previous question',
				  titleClick: true,
				  description:  false,
				  legend:       true,
				  titleClick:   true,
				  titleTarget:  '#title-target'
				}); 
				    

});
</script>


