<?php  
	$allow[1] = false;
	$allow[2] = false;

	switch ($this->step){
		case 1 : $allow[1] = true;
		break;
		case 2 : $allow[2] = true;
		break;
	
	}
  ?>
   
  <div class="fl-cnt-100">
  <ul class="nav nav-pills">
  	  <li class="<?php echo($allow[1] == true ? "active" : "disable" );?>"><a href="/member/my-project/task/id/<?php echo $this->project->id?>">Tasks</a></li>
 	<li class="<?php echo($allow[2] == true ? "active" : "disable" );?>"> <a href="/member/my-project/level/id/<?php echo $this->project->id?>">Levels</a></li>
   </ul>
</div>