<?php 
$this->step = 5;
echo $this->partial('my-project/my-project-navigation.phtml',array("step" => $this->step,"project" => $this->project));
?>

<div class="fl-cnt-100">
  <div class="alert alert-info">
     Want to express your project/idea progression as more than just tasks/questions completed? Think of this as your short-length (500 words) journal/blog space to update the community on you and your project. 
  </div>
</div>

<div class="fl-cnt-100 create-new">
  <a href="/member/my-project/update-create/id/<?php echo $this->project->id?>" title="create new update"><span class="green"><img src="/media/slepice-site/1.0.0/img/icon_new_project.jpg" alt="create new update icon" /> create new udpate</span></a>
</div>


<div class="fl-cnt-100 fl-top20">
<!-- Updates Table -->
<?php if (count($this->paginator) > 1 )echo $this->paginationControl($this->paginator, 'Elastic', 'partials/pagination-control-bootstrap.phtml'); ?> 

<?php if (count($this->paginator)) {?>
        <table class="table table-striped">
        <thead>
    		<tr>
    			<th>Title</th>
    			<th>Created</th>
    			<th>Last Modification</th>
    			<th>Actions</th>
    		</tr>
    	</thead>
    <tbody>
    <?php foreach ($this->paginator as $update){ ?>
    	<tr>
    	<td><?php echo $update->title; ?></td>
		<td><?php echo $update->created->format('Y/m/d'); ?></td>		
		<td><?php echo $update->modified->format('Y/m/d'); ?></td>		
    	<td>
          <div class="input-prepend input-append">
            <a href="/member/my-project/update-edit/id/<?php echo $this->project->id?>/update_id/<?php echo $update->id ?>" class="btn btn-info"><i class="icon-wrench icon-white"></i> Edit Update</a><a href="/member/my-project/update-delete/id/<?php echo $this->project->id?>/update_id/<?php echo $update->id ?>" class="btn btn-danger"><i class="icon-remove icon-white"></i> Delete</a>
          </div>
    	</td>			
    	</tr>	 		
    <?php } ?>
    </tbody>
    </table>
<?php }?>
</div>





