<h2>Slideshow</h2>

  <div class="fl-cnt-100 fl-top">
  			 
                
 <div class="fl-list-project">
  
     <?php for($i=1;$i < 6;$i++) {$f = "form_slot_".$i; ?>

     <?php $project = $this->$f->getProject(); 
     		if($project) { 
     ?>
       
                  <div class="fl-cnt-20">
                    <div class="fl-project-thumb">
                      <div class="inner-5">
						 <a href="/project/index/index/id/<?php echo $project->id?>" title="<?php echo $project->title; ?>"> 
                        <img alt="<?php echo $project->title; ?> - main picture" src="<?php echo $project->getPictureUrl('small'); ?>" />
                    	 </a>
 						<div class="fl-level">
                        <?php 
                        // Display Current Level
                        $array[1] = array('fl_level1','bar','bar');
                        $array[2] = array('fl_level2','fl_level2','bar');
                        $array[3] = array('fl_level3','fl_level3','fl_level3');
                        foreach($array[$project->level] as $c){ ?>
                                            <div class="progress fl-small-bar">
                                                  <div class="<?php echo $c?>"></div>
                                            </div>
                        <?php } ?>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="fl-cnt-50">
                    <div class="inner-list-project">
                      <div class="fl-cnt-100">
                        <h3 class="fl-list-project-h3"><?php echo $project->title; ?></h3>
                        <p class="fl-list-project-info"><i class="icon-folder-close"></i> <?php echo $project->category->name; ?>,
                         <i class="icon-eye-open"></i> <?php echo $project->getCountFollowers();?> Followers</p>
                      </div>
                    </div>
                  </div>
                  
                  <?php } 
                  // no project selected
                  else { ?>
                  	<div class="fl-cnt-20">&nbsp;</div>
                    <div class="fl-cnt-50">&nbsp;</div>
                  <?php }
                  ?>
                  
	   			<div class="fl-cnt-30 fl-slot">
			     	  <form class="fl-slot" action="<?php echo $this->$f->getAction(); ?>"  method="<?php echo $this->$f->getMethod(); ?>" >
			     		<fieldset>
						     <?php echo $this->$f->project_id; ?>
						     <?php echo $this->$f->slot_position; ?>
						     <?php echo $this->$f->submit; ?>
						     
			     		</fieldset>
			     		</form>
			     	</div>
		
	 <div class="fl_thin_divider"></div>
		

	 <?php }?>
	 
	                
	 </div>
               

  </div>
	 
