<?php
  $this->step = 2;
  echo $this->partial('profile-setting/profile-setting-navigation.phtml',array("step" => $this->step));
?>
                <div class="fl-cnt-50">
                  <h3>Current picture:</h3>
                  <div class="fl_thin_divider"></div>
                  <div class="fl-cnt-100 text-center">
                    <img src="<?php echo $this->loggedMember->getProfilePictureUrl('large').'?foo='.time()?>" alt="<?php echo $this->loggedMember->name;?> ~ Profile Picture" class="fl-img" />
                  </div>
                </div>
                <div class="fl-cnt-50">
                  <h3>New picture:</h3>
                  <div class="fl_thin_divider"></div>
                  <div class="fl-cnt-100">
                    <div class="alert alert-info">
                      <span class="label label-info">Info</span>
                      Image will be automatically cropped. Try to upload image which has resolution 200x200 to have the best image quality and proportion.
                    </div>
                  </div>
<div class="fl-cnt-50">
	<?php  echo $this->form; ?>
</div>
</div>

  
    