
  <?php
  $this->step = 3;
  echo $this->partial('profile-setting/profile-setting-navigation.phtml',array("step" => $this->step));
  ?>



<div class="fl-cnt-100">
<form class="form-horizontal fl-my-skills-form" action="<?php echo $this->form->getAction(); ?>"  method="<?php echo $this->form->getMethod(); ?>" >
  <fieldset><legend class="hide">Your role(s) in this project:</legend>
                 <div class="fl-cnt-100 fl-bottom40">
                   <div class="fl-choosing-roles-top">
                          <div class="fl-choosing-roles-top-left">
                            
                          </div>
                          <div class="fl-choosing-roles-top-right">
                            
                          </div>
                   </div>
                   <div class="fl-choosing-roles-middle">
                          <div class="fl-choosing-roles-list">
                            <ul class="fl-choosing-roles">
                              <?php 
                              // generate all role options
                              $arrayRoles = \App\Entity\ProjectRole::getRolesArray();
                              foreach($arrayRoles as $role){	
								$r = "role_".$role;
								$t = "role_".$role."_tags"; ?>	
                              <li id="<?php echo $r; ?>"> <?php echo $this->form->$r; ?>
                                <label for="<?php echo $r; ?>">
                                  <div class="fl-skill">
                                    <div class="fl-skill-img30">
                                      <img src="/media/slepice-site/1.0.0/img/role_<?php echo $role;?>.png" alt="<?php echo $role;?> role icon" />
                                    </div>
                                    <div class="fl-skill-text">
                                      <div class="fl-skill-text-roledescription30">
                                       <?php echo $role;?>
                                      </div>
                                    </div>
                                  </div>
                                </label>
                                  <?php echo $this->form->$t; ?>
                              </li>
							  <?php  } ?>
                            </ul>
                          </div>
                          <div class="fl-choosing-roles-description">
                            <h4>Starter</h4>
                            <div class="fl_thin_divider"></div>
                            <p>The founder of the project. The seeker of solutions to problems, the visionary. The (wo)man with the plan. This person is the heart and soul of the beginning of the project. The starter will begin cobbling together the framework of the project and add on key people throughout the journey to make the idea a reality.</p>
                          </div>
                   </div>
                   <div class="fl-choosing-roles-bottom">
                          <div class="fl-choosing-roles-bottom-left">
                            
                          </div>
                          <div class="fl-choosing-roles-bottom-right"> 
                          </div>
                   </div>
                 </div>

  <div class="hide">
    <div id="hide_role_starter">
      <h4>Starter</h4>
      <div>The founder of the project. The seeker of solutions to problems, the visionary. The (wo)man with the plan. This person is the heart and soul of the beginning of the project. The starter will begin cobbling together the framework of the project and add on key people throughout the journey to make the idea a reality.</div>
    </div>

    <div id="hide_role_leader">
      <h4>Leader</h4>
      <div>Any group is lost without one. You might be the leader, or you might need someone to take the helm. In either case, this person is essential. When met with difficult decisions, who is going to be the ‘go-to’ person to make sure the right call is made, in a timely fashion? This person is a born communicator who thrives under pressure and can remain focused on the end-goal while maneuvering through all of the obstacles along the way. If and when your project makes it way from theory to reality, this is the person in the best position to begin running the business.</div>
    </div>

    <div id="hide_role_grower">
      <h4>Grower</h4>
      <div>The marketer of the project. The mouth. The evangelist. This person’s main goal is to get as many people exposed to your fabulous idea and communicate its value by talking everyone’s ear off. As such, (s)he is constantly striving to make things bigger, better, and scalable. This person’s skills as a communicator might even be stronger than the Leader’s, so get them out there shaking hands and kissing babies!</div>
    </div>

    <div id="hide_role_builder">
      <h4>Builder</h4>
      <div>The architect of the project. There may be five builders, there may be ten, there may only be one. It could be a programmer, a designer, an artist, an engineer, etc. This person is extremely creative, shares your vision, and has the technical chops to help work the idea into a viable product.</div>
    </div>

    <div id="hide_role_adviser">
      <h4>Adviser</h4>
      <div>The adviser is essential to your project. They may be advising on five other projects based on extensive technical expertise, or focusing all of their attention on your concept to help make sure it reaches its goals. The advisor either has a lot of experience in your field, or a highly specialized technical understanding of your market. The adviser will help to digest all of the crowdsourced feedback your project will receive, and help steer it down the right avenues of development.</div>
    </div>
  </div>
		
		<div class="fl-cnt-100">
			<?php echo $this->form->actions; ?>
		</div>

</fieldset>
</form>
</div>


  <script type="text/javascript" src="<?=$this->baseUrl('/media/slepice-site/1.0.0/js/description.js')?>"></script>

 
