<!DOCTYPE HTML>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title><?= (!is_null($this->pageTitle)) ? $this->pageTitle : " Default "; ?> </title>
  <meta name="description" content="">
  <meta name="author" content="">
  <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="<?=$this->baseUrl('/media/data-tables-1.9.1/css/data-table-bootstrap2-additional.css')?>">
    <?= $this->action('lib', 'index', 'site');  // libraries ?>
    <link rel="stylesheet" href="<?=$this->baseUrl('/media/slepice-site/1.0.0/css/flow_css.css')?>">

</head>
<body>
	<div id="fl-top">
   <div id="fl-container">
    <p>What is FLO~? How does it work? <i class="icon-share-alt"></i> <a href="/index/learn-more" title="Learn more about FLO~">Learn more!</a></p>
   </div>
 </div>
 
 	<div id="fl-container">
 	<?= $this->action('menu-debug', 'menu', 'project');  ?>  
   <div class="container">
     <?= $this->action('header', 'index', 'site');  ?>
   </div>
  <div id="fl-content">
   <div class="container"> 
	<?= $this->action('breadcrumbs', 'index', 'site');  ?>
	 

    <div class="row">
       <div class="span11">
 	<!-- Bootstrap messaging generator -->
 	<div class="fl-cnt-100">
	     <?php echo $this->flashMessenger() ; ?>
	 </div>
  	<?php echo $this->layout()->content; ?>
  	    
	        <div class="span4 fl-sidebar-bg">
	    	    <div class="inner">
                <!-- Levels and Tasks module -->
                <h3 class="fl-sidebar-h3-first">Project Level</h3>
                <div class="fl_thick_divider"></div>
                <div class="fl-project-level">
               
                  <div class="fl-level">
					<?php // Display Current Level
					$array[1] = array('fl_level1','bar','bar');
					$array[2] = array('fl_level2','fl_level2','bar');
					$array[3] = array('fl_level3','fl_level3','fl_level3');
					$i = 1;
					foreach($array[$this->project->level] as $c){ ?>
					  <div class="progress lvl<?php echo $i; $i++;?>">
					    <div class="<?php echo $c?>"></div>
					  </div>
					<?php } ?>
				  </div>


                  <p class="fl-project-level-info"><a href="" title="Learn more about Levels">Learn more about Levels</a></p>
                </div>


                <?php
	                echo $this->action('task', 'widget', 'project',array("id" => $this->project->id));
	            ?>
	    	      
                <h3 class="fl-sidebar">Team</h3>
                <div class="fl_thick_divider"></div>
                <div class="fl-team">
                  <div class="fl-team-author">
                    <div class="fl-team-author-roles">
                      <?php 
                 	  foreach($this->project->getCreatorRolesArray() as $r){
                 	  	echo  '<img src="/media/slepice-site/1.0.0/img/role_'.$r.'.png" alt="'.$r.'" title="'.$r.'" /> ';
                 	  }?>
                    </div>
                    <div class="fl-team-author-created">
                      <span>Project created by</span>
                      <span class="fl-team-author-name"><?php echo $this->project->user->name;?></span>
                    </div>
                  </div>
                 

                  <div class="fl_thin_divider"></div> 
                      <!-- Form Applications for Level 1 -->
                      <?php 
                        if($this->project->level == 1)          
                             echo $this->action('application', 'widget', 'project',array("id" => $this->project->id));?>
                      <!-- Form Applications for Level 2 -->
                       <?php if($this->project->level == 2)
                            echo $this->action('application-level2', 'widget', 'project',array("id" => $this->project->id));?>
                </div>


                <h3 class="fl-sidebar">Passion Slider</h3>
                <div class="fl_thick_divider"></div>
                <div class="fl-passion-slider">
                <div class="progress fl-passion-bar">
                  <div class="bar fl-bar" style="width: <?php echo $this->project->priority*10;?>%;"></div>
                </div>
                </div>
				
				<!-- Polls widget -->
   				<?php echo $this->action('poll', 'widget', 'project',array("id" => $this->project->id));?>
                
				<!-- Similar projects widget -->
				  <?php echo $this->action('similar', 'widget', 'project',array("id" => $this->project->id));?>
	         </div>
         </div>
       </div>
     </div>
   

<div id="bottom">
        <?= $this->action('footer', 'index', 'site');  ?>
   </div>

  </div>
</div>

<div id="fl-bottom-line">
  <p>&copy; 2012 SLEPICE / ZF</p>
</div>


    
 <script type="text/javascript">  
			var Models = {
			init: function(config){
				// ajax setup
				$.ajaxSetup({
					url: "/site/index/ajax-index", 
					type: 'GET',
					dataType: 'json',
				});
				
				this.config = config;
				this.bindEvents();
			},
				
			bindEvents: function(){
				//this.config.likeMemberBtn.css("color","red");
				this.config.likeMemberBtn.on("click", this.likeMember);		
				this.config.likeProjectBtn.on("click", this.likeProject);		
				
			},
				
			// likeMember
			likeMember: function(e) {
				var follower_count = $(this).closest('.info').find(".follower-count");
				console.log(follower_count);
				var val = $(this).text();
				var user_id = $(this).attr("id");
				if(val == 'Like') {
					$(this).html("Dislike");
				}else {
					$(this).html("Like");
				} 	
					// send data to server
					$.ajax({
						data:   "&_method=like-member&&friend_id="+user_id, // take data from the form and send it to the method update
					}).done(
							function (results){
								// set new value for followers		
								follower_count.html(results.data.count_friends); // number of current friends
							}
					);			
				e.preventDefault();
			},
			// likeProject
			likeProject: function(e) {
				var follower_count = $(this).closest('.info').find(".follower-count");
				console.log(follower_count);
				var val = $(this).text();
				var project_id = $(this).attr("id");
				if(val == 'Like') {
					$(this).html("Dislike");
				}else {
					$(this).html("Like");
				} 	
					// send data to server
					$.ajax({
						data:   "&_method=like-project&&project_id="+project_id, // take data from the form and send it to the method update
					}).done(
							function (results){
								// set new value for followers		
								follower_count.html(results.data.count_followers); // number of current friends
							}
					);			
				e.preventDefault();
			}
			};
			
			// like models
			Models.init({
				likeMemberBtn: $(".like-member"), //select a with class 
				likeProjectBtn: $(".like-project"), //select a with class 
				 
			});


 </script>

 <script src="/media/jquery.simpletip-1.3.1/jquery.simpletip-1.3.1.js"></script>
 <script src="/media/slepice-site/1.0.0/js/tooltips-tasks.js"></script>
 
</body>
</html>