<h2>Start new project</h2>

<?php 
echo $this->partial('project/create-project-navigation.phtml',array("step" => $this->step));
?>

<div class="fl-cnt-100">
	<div class="well">
	  <div id="title-target"></div>
	</div>  
</div> 

<div class="fl-cnt-100">
<?php  echo $this->form;   ?>
</div>


<!-- Load jQuery build -->
<script type="text/javascript" src="<?=$this->baseUrl('/media/jquery.stepy-1.1.0/js/jquery.validate.min.js')?>"></script>
<script type="text/javascript" src="<?=$this->baseUrl('/media/jquery.stepy-1.1.0/js/jquery.stepy.js')?>"></script>
<script type="text/javascript">
$(document).ready(function()
		{	// disable cache
			 $.ajaxSetup ({cache: false });  	
			// $("#submit").hide();
			 $('#step').stepy({
				 next: function(index) {
				    if(index==16){
					   	// $("#submit").show();	
					}
					}
				 ,
				  finishButton:	false,
				  nextLabel:      'Next question',
				  backLabel:      'Previous question',
				  titleClick: true,
				  description:  false,
				  legend:       true,
				  titleClick:   true,
				  titleTarget:  '#title-target'
				}); 
				    

});



</script>