<h2>Start new project</h2>

<?php 
echo $this->partial('project/create-project-navigation.phtml',array("step" => $this->step));

?>
<div class="fl-cnt-100">
  <div class="alert alert-info">
    <span class="label label-info">Info</span>
    Image will be automatically cropped in largest size.
  </div>
</div>

<div class="fl-cnt-100">
  <div id="alert-area"></div>
</div>

<div class="fl-cnt-100">
<form id="imageform" enctype="multipart/form-data" class="form-horizontal" action="/member/project/ajax-create-project-step-two/_method/create" method="post">
  <fieldset id="fieldset-CreateProjectChooseProfilePhoto">
    <legend class="hide">Step 2 / Choose Picture</legend>
  <div id="preview">
  <?php 
	// display picture from the previous
	if(Zend_Session::namespaceIsset('projectStep2')){
		$session = Zend_Session::namespaceGet('projectStep2');
		if(isset($session['secondFormData'])){
			echo '<div class="fl-cnt-100 text-center fl-bottom20"> <img src="'.$session['secondFormData']['webUrl'].'?foo='.time().'" alt="Project picture" class="fl-img"/> </div>';
		}	
	}
  ?>
  </div> 
 <div class="control-group">
  <label for="project_picture" class="control-label optional">Choose Picture</label>
 <div class="controls">
<input type="file" name="photoimg" id="photoimg" class="input-file">
<p class="help-block">Max size 4MB (jpg,jpeg,png)</p></div>
</div>
</fieldset>
<div class="form-actions">
    <a class="btn btn-info" href="<?php echo $this->url(array('module' => "member",'controller'=>'project','action'=>'create-project-step-one'),null,true)?>">Previous step</a>
    <a class="btn btn-info" id="button-continue" href="<?php echo $this->url(array('module' => "member",'controller'=>'project','action'=>'create-project-step-three'),null,true)?>">Next step</a>

</div>
</form>
</div>




<?php // echo $this->form;   ?>


<!-- Load jQuery build -->
<script type="text/javascript" src="<?=$this->baseUrl('/media/tools/jquery.form.js')?>"></script>

<script type="text/javascript">
$(document).ready(function()
{
	// disable cache
	 $.ajaxSetup ({cache: false });  
	 <?php 
	  // display picture from the previous
	  if(!Zend_Session::namespaceIsset('projectStep2')){
	  echo '$("#button-continue").hide();';}
	  ?>
	  
	   var options = { 
		        target: '#preview',   // target element(s) to be updated with server response 
		        success: showResponse,  // post-submit callback 
		        error: showError,  // post-submit callback 
		        dataType: 'json'        // 'xml', 'script', or 'json' (expected server response type) 
	  }; 

		$('#photoimg').live('change', function()
		{
			$("#preview").html('');
			$("#preview").html('<img src="/media/slepice-site/1.0.0/img/loader.gif" alt="Processing picture..."/>');
			$("#imageform").ajaxForm(options).submit();
		});
 
		// post-submit callback 
		function showResponse(responseText, statusText, xhr, $form)  { 
			console.log(responseText);
			
			if(responseText.respond == "error"){
				newAlert('error', responseText.message);
				$("#preview").html('');
			}else{
				$("#preview").html('');
				$("#preview").html('<div class="fl-cnt-100 text-center fl-bottom20"> <img src="'+responseText.web_url+'?foo=' + new Date().getTime()+'" alt="Profile Picture" class="fl-img"/> </div>');
				$("#button-continue").show();
				newAlert('success', responseText.message);
			} 
		} 

		// post-submit callback 
		function showError(responseText, statusText, xhr, $form)  { 
		    alert('status: ' + statusText + '\n\nresponseText: \n' + xhr.toSource() + 
		        'We are sorry, but something is wrong. Try to check if your image is allright.'); 
		} 		
});
</script>
