<div class="fl-cnt-100">
   <?php  
	$percentage = 20;
	$allow[1] = false;
	$allow[2] = false;	$allow[3] = false;	$allow[4] = false;$allow[5] = false;
	switch ($this->step){
		case 1 : $allow[1] = true;
				 break; 
		case 2 : $percentage = 40; $allow[2] = true;
				 break;
		case 3 : $percentage = 60; $allow[3] = true;
				 break;
		case 4 :$percentage = 80; $allow[4] = true;
				break;
		case 5 : $percentage = 100; $allow[5] = true;
				 break;	 
	}
  ?>

    <div class="btn-group fl-creating-steps">
	  <a class="btn btn-large <?php echo($allow[1] == true ? "active" : "disable" );?>" href="<?php echo $this->url(array('module' => "member",'controller'=>'project','action'=>'create-project-step-one'),null,true)?>">#1 / General Info</a>
	  <a class="btn btn-large <?php echo($allow[2] == true ? "active" : "disable" );?>" href="<?php echo $this->url(array('module' => "member",'controller'=>'project','action'=>'create-project-step-two'),null,true)?>">#2 / Project Picture</a>
	  <a class="btn btn-large <?php echo($allow[3] == true ? "active" : "disable" );?>" href="<?php echo $this->url(array('module' => "member",'controller'=>'project','action'=>'create-project-step-three'),null,true)?>">#3 / Team </a>
	  <a class="btn btn-large <?php echo($allow[4] == true ? "active" : "disable" );?>" href="<?php echo $this->url(array('module' => "member",'controller'=>'project','action'=>'create-project-step-four'),null,true)?>">#4 / Survey </a>
	  <a class="btn btn-large <?php echo($allow[5] == true ? "active" : "disable" );?>" href="<?php echo $this->url(array('module' => "member",'controller'=>'project','action'=>'create-project-step-five'),null,true)?>">#5  / Publishing </a>
	</div>
</div>