<h2>Start new project</h2>

<?php 
echo $this->partial('project/create-project-navigation.phtml',array("step" => $this->step));

?>

<div class="fl-cnt-100">
  <div class="alert alert-info">
	 This is step one of the project creation process. It’s the first big step forward, marked by “putting pen to paper” on your idea. By doing this, you are beginning a process that will guide you in creating an actionable plan to build a business around. Not ready to finish every step in one go? That’s OK. The information you input is saved at every step of the process so you can come back to it later.
  </div>
</div>

<div class="fl-cnt-100">
<?php  echo $this->form;   ?>
</div>

	<!-- Load jQuery build -->
	<script type="text/javascript" src="<?=$this->baseUrl('/media/tiny_mce/tiny_mce.js')?>"></script>
	<script type="text/javascript">
		tinyMCE.init({
		        // General options
		        mode : "textareas",
		        theme : "simple",
		        valid_styles : { '*' : 'color,font-size,font-weight,text-decoration' },
		        mode : "exact",
		        elements : "content", // just for textarea with id content   
		        plugins : "autolink",
		        invalid_elements: "span",
		        content_css : "/media/slepice-site/1.0.0/css/flow_css_tinymce.css",
	});
	</script>
