<h2>Start new project</h2>

<?php 
echo $this->partial('project/create-project-navigation.phtml',array("step" => $this->step));
?>

<div class="fl-cnt-100">
  <div id="alert-area"></div>
</div>

<div class="fl-cnt-100">
			<form>
              <fieldset>
                <legend class="hide">Your role(s) in this project:</legend>
                <h3 class="fl-bottom10">Your role(s) in this project:</h3>
                <div class="fl-cnt-100 fl-bottom40">
                  

                        <div class="fl-choosing-roles-top">
                          <div class="fl-choosing-roles-top-left">
                            
                          </div>
                          <div class="fl-choosing-roles-top-right">
                            
                          </div>
                        </div>
                        <div class="fl-choosing-roles-middle">
                          <div class="fl-choosing-roles-list">
                            <ul class="fl-choosing-roles">
                              <li>
                                <input type="checkbox" name="" id="" />
                                <label for="">
                                  <div class="fl-skill">
                                    <div class="fl-skill-img30">
                                      <img src="/media/slepice-site/1.0.0/img/role_starter.png" alt="starter role icon" />
                                    </div>
                                    <div class="fl-skill-text">
                                      <div class="fl-skill-text-roledescription30">
                                        Starter
                                      </div>
                                    </div>
                                  </div>
                                </label>
                              </li>
                              <li>
                                <input type="checkbox" name="" id="" />
                                <label for="">
                                  <div class="fl-skill">
                                    <div class="fl-skill-img30">
                                      <img src="/media/slepice-site/1.0.0/img/role_leader.png" alt="leader role icon" />
                                    </div>
                                    <div class="fl-skill-text">
                                      <div class="fl-skill-text-roledescription30">
                                        Leader
                                      </div>
                                    </div>
                                  </div>
                                </label>
                              </li>
                              <li>
                                <input type="checkbox" name="" id="" />
                                <label for="">
                                  <div class="fl-skill">
                                    <div class="fl-skill-img30">
                                      <img src="/media/slepice-site/1.0.0/img/role_grower.png" alt="grower role icon" />
                                    </div>
                                    <div class="fl-skill-text">
                                      <div class="fl-skill-text-roledescription30">
                                        Grower
                                      </div>
                                    </div>
                                  </div>
                                </label>
                              </li>
                              <li>
                                <input type="checkbox" name="" id="" />
                                <label for="">
                                  <div class="fl-skill">
                                    <div class="fl-skill-img30">
                                      <img src="/media/slepice-site/1.0.0/img/role_builder.png" alt="builder role icon" />
                                    </div>
                                    <div class="fl-skill-text">
                                      <div class="fl-skill-text-roledescription30">
                                        Builder
                                      </div>
                                    </div>
                                  </div>
                                </label>
                              </li>
                              <li>
                                <input type="checkbox" name="" id="" />
                                <label for="">
                                  <div class="fl-skill">
                                    <div class="fl-skill-img30">
                                      <img src="/media/slepice-site/1.0.0/img/role_adviser.png" alt="adviser role icon" title="" />
                                    </div>
                                    <div class="fl-skill-text">
                                      <div class="fl-skill-text-roledescription30">
                                        Adviser
                                      </div>
                                    </div>
                                  </div>
                                </label>
                              </li>
                            </ul>
                          </div>
                          <div class="fl-choosing-roles-description">
                            <h4>Name of the role</h4>
                            <div class="fl_thin_divider"></div>
                            <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>
                          </div>
                        </div>
                        <div class="fl-choosing-roles-bottom">
                          <div class="fl-choosing-roles-bottom-left">
                            
                          </div>
                          <div class="fl-choosing-roles-bottom-right">
                            
                          </div>
                        </div>
                </div>

                <div class="fl-cnt-100 fl-bottom40">
                  <div class="alert alert-info">
                    <p><span class="label label-info">Info</span> Description what is role widget for. Description what is role widget for. Description what is role widget for. Description what is role widget for. Description what is role widget for. Description what is role widget for. Description what is role widget for. Description what is role widget for. Description what is role widget for. Description what is role widget for. Description what is role widget for. Description what is role widget for.</p>
                    <div class="fl-role-widget">
                      <input type="checkbox" name="" id="" /><label for="">Disable role widget</label>
                    </div>
                  </div>
                </div>
              </fieldset>
      </form>
</div>

<div class="fl-cnt-100">
  <?php  echo $this->form;   ?>
</div>



<script type="text/javascript">
$(document).ready(function()
{	// disable cache
	 $.ajaxSetup ({cache: false });  

	// check at init	
	displayVals();
	$('#role_widget_disable').change(displayVals);
		 function displayVals() {
			// if the widget is disable, hide questions
			if($('#role_widget_disable').is(':checked')){
			 $('#fieldset-role_widget_survey').hide();
			}else{
				 $('#fieldset-role_widget_survey').show();
			}
			
 }
				    
	   		
});
</script>
