<!DOCTYPE HTML>

<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>Project-F Beta / <?= (!is_null($this->pageTitle)) ? $this->pageTitle : " Default "; ?> </title>
  <meta name="description" content="">
  <meta name="author" content="">

  <meta name="viewport" content="width=device-width,initial-scale=1">
  
   <?= $this->action('lib', 'index', 'site');  // libraries ?>

   <link rel="stylesheet" href="<?=$this->baseUrl('/media/slepice-site/1.0.0/css/flow_css.css')?>">

</head>
<body>
 <div id="fl-container">
  <?= $this->action('menu-debug', 'menu', 'project');  ?>
   <div class="container">
     <?= $this->action('header', 'index', 'site');  ?>
   </div>

<div id="fl-content">
     <div class="container"> 
  <?= $this->action('breadcrumbs', 'index', 'site');  ?>
   
          
  <!-- Bootstrap messaging generator -->
  <div class="fl-cnt-100">
     <?php echo $this->flashMessenger() ; ?>
  </div>
  <?php echo $this->layout()->content; ?>
  
   <div class="span4 fl-sidebar">
              <div class="inner">
                <h3 class="fl-sidebar-h3-first">My Skills</h3>
                <div class="fl_thick_divider"></div>
                
                <div class="fl-cnt-100">
                
                <?php 
                foreach($this->user->specificRoles as $r){
                	?>
                	
                	 <div class="fl-skill">
                    <div class="fl-skill-img40">
                      <img src="/media/slepice-site/1.0.0/img/role_<?php echo $r->name;?>.png" alt="<?php echo $r->name;?>" title="<?php echo $r->name;?>" />
                    </div>
                    <div class="fl-skill-text">
                      <div class="fl-skill-text-role">
                       <?php echo $r->name;?>
                      </div>
                      <div class="fl-skill-text-tags">
                       <?php 
                       		foreach($r->tags as $t){
                       			echo $t->name." ";
                       		}
                       ?>
                      </div>
                    </div>
                  </div>
                	

                <?php 
                
                }
                
                
                ?>
                 

                  <div class="fl_thin_divider"></div>

                </div>

                
                	<?php echo $this->action('widget-my-favourite-project', 'profile', 'member',array("id" => $this->user->id));?>
                	<?php echo $this->action('widget-my-favourite-member', 'profile', 'member',array("id" => $this->user->id));?>
                
                
              </div>
            </div>


     <div id="bottom">
        <?= $this->action('footer', 'index', 'site');  ?>
     </div>
     
    </div>
</div>

  
 <div class="fl-bottom-line">
  <p>&copy; 2012 SLEPICE / ZF <br />
<small><?php echo $this->translate("Today is"); ?> <b><?php echo new Zend_Date($this->timestamp); ?></b> <?php if ($this->cachedTimestamp) { ?>(<?php echo $this->translate("Timestamp served from Memcached");?>)<?php } ?></small></p>
 </div>

</body>
</html>