<!-- Carousel Slideshow Module -->
<div class="row">
  <div class="fl-cnt-100">
     <div id="myCarousel" class="carousel slide">
       <div class="carousel-inner">
          <?php 
    $active = true;
    for($i=1;$i<6;$i++){
      $project = $this->slideshow->getProject($i);
      if($project){ ?>
    <div class="item <?php if($active == true) {echo "active";$active = false;} // first project is set to be active?>">
       <div class="span5"> 
         <div class="fl_slider_text">
           <h2><?php echo $project->title; ?></h2>
            <span class="author"><i class="icon-user"></i> <a href="/member/profile/index/id/<?php echo $project->user->id;?>" title=""><?php echo $project->user->name;?></a></span>

<?php switch($project->level){
  case '1': ?>
                     <div class="fl-level">
                        <div class="progress">
                          <div class="fl_level1"></div>
                        </div>
                        <div class="progress">
                          <div class="bar"></div>
                        </div>
                        <div class="progress">
                          <div class="bar"></div>
                        </div>
                      </div>
<?php ; break;
  case '2': ?>

                      <div class="fl-level">
                        <div class="progress">
                          <div class="fl_level2"></div>
                        </div>
                        <div class="progress">
                          <div class="fl_level2"></div>
                        </div>
                        <div class="progress">
                          <div class="bar"></div>
                        </div>
                      </div>
<?php ; break;
  case '3': ?>

                      <div class="fl-level">
                        <div class="progress">
                          <div class="fl_level3"></div>
                        </div>
                        <div class="progress">
                          <div class="fl_level3"></div>
                        </div>
                        <div class="progress">
                          <div class="fl_level3"></div>
                        </div>
                      </div>
<?php ;
}?>
          <div class="fl-cnt-100 fl-top10">
            <div class="fl-cnt-100 fl-height-100">
              <p><?php echo $project->pitchSentence; ?></p>
            </div>
            <p class="info">
              <span class="category"><i class="icon-folder-close"></i> Design</span>
              <span class="followers"><i class="icon-eye-open"></i> <strong>56</strong> followers</span>
              <span class="like"><i class="icon-thumbs-up"></i> <a href="" title="">Like</a></span>
            </p>
          </div>
            
            <div class="fl_slider_roles">
              <div class="fl_slider_role">
                <img src="/media/slepice-site/1.0.0/img/role60x60_1.png" alt="" />
              </div>
              <div class="fl_slider_role">
                <img src="/media/slepice-site/1.0.0/img/role60x60_2.png" alt="" />
              </div>
              <div class="fl_slider_role">
                <img src="/media/slepice-site/1.0.0/img/role60x60_3.png" alt="" />
              </div>
              <div class="fl_slider_role">
                <img src="/media/slepice-site/1.0.0/img/role60x60_4.png" alt="" />
              </div>
              <div class="fl_slider_role">
                <img src="/media/slepice-site/1.0.0/img/role60x60_5.png" alt="" />
              </div>
            </div> 
          </div>
        </div>
        <div class="span6 text-right fl-top-project-img"> 
          <a href="/project/index/index/id/<?php echo $project->id?>" title="<?php echo $project->title; ?>">
           <img alt="<?php echo $project->title; ?> - main picture" src="/storage/projects/<?php echo $project->dir."/".$project->getPicture('large'); ?> " class="fl-img"/>
          </a>
         
       </div> 
    </div>  
    <?php
      }
   }
   ?>
          
        </div>
            <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
      </div>
      </div>
</div>