<?php 
$projects = $this->slideshow->getAllProjectsArray();
if(empty($projects)){ echo "No projects to display in slideshow."; return; }	
?>

<!-- Carousel Slideshow Module -->
<div class="row">
  <div class="fl-cnt-100 fl-minheight-100">
     <div id="myCarousel" class="carousel slide">
       <div class="carousel-inner">
          <?php 
    $active = true;
   	foreach($projects as $project){
    ?>
    <div class="item <?php if($active == true) {echo "active";$active = false;} // first project is set to be active?>">
       <div class="span5"> 
         <div class="fl_slider_text">
           <h2><?php echo $project->title; ?></h2>
            <span class="author"><i class="icon-user"></i> <a href="/member/profile/index/id/<?php echo $project->user->id;?>" title=""><?php echo $project->user->name;?></a></span>

  						<div class="fl-level">
                        <?php 
                        // Display Current Level
                        $array[1] = array('fl_level1','bar','bar');
                        $array[2] = array('fl_level2','fl_level2','bar');
                        $array[3] = array('fl_level3','fl_level3','fl_level3');
                        foreach($array[$project->level] as $c){ ?>
                                            <div class="progress">
                                                  <div class="<?php echo $c?>"></div>
                                            </div>
                        <?php } ?>
                        </div>
            
          <div class="fl-cnt-100 fl-top10">
            <div class="fl-cnt-100 fl-height-100">
              <p><?php echo $project->pitchSentence; ?></p>
            </div>
            <p class="info">
              <span class="category"><i class="icon-folder-close"></i> <?php echo $project->category->name;?></span>
              <span class="followers"><i class="icon-eye-open"></i> <strong><?php echo $project->getCountFollowers();?></strong> followers</span>
                <span class="like"><i class="icon-thumbs-up"></i> 
                         <?php
                         // like dislike solution 
                         if(!$project->isFollower($this->loggedMember)) {
						 ?> <a href="" title="" class="like-project" id="<?php echo $project->id;?>" >Like</a>
						 <?php } else { ?>
                            <a href="" title="" class="like-project" id="<?php echo $project->id;?>" >Dislike</a>
                         <?php } ?>
                         </span>
            </p>
          </div>
            
            <div class="fl_slider_roles">
                 <?php 
                
                       		 $display = false;
                        // if level 1 display all logos   
						if($project->level == 1) {
                        $freePositions = \App\Entity\ProjectRole::getRolesArray();
							$display = true;
						}
						if($project->level == 2){
                       // if level 2 display free positions
                        $facadeProject = new \App\Facade\Project\TeamFacade($this->em);
                    	$freePositions = $facadeProject->findFreeUniqueProjectRolesForProjectArray($project->id); 
							$display =  true;	
						}
						
						if($display){
						
                    	// if level 3 = have no idea what to display or not
                    	foreach ($freePositions as $r){
                    		
                    		echo '<div class="fl_project_thumb_role">';
                    		echo '<img src="/media/slepice-site/1.0.0/img/role60x60_'.$r.'.png" alt="'.$r.'" title="'.$r.'" />';
                    		echo '</div>';
                    	}
						} 
                    	?>
            </div> 
            
            
                
                   
                    
          </div>
        </div>
        <div class="span6 text-right fl-top-project-img"> 
          <a href="/project/index/index/id/<?php echo $project->id?>" title="<?php echo $project->title; ?>">
           <img alt="<?php echo $project->title; ?> - main picture" src="/storage/projects/<?php echo $project->dir."/".$project->getPicture('large'); ?> " class="fl-img"/>
          </a>
         
       </div> 
    </div>  
  <?php 
   	}
  ?>        
        </div>
            <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
      </div>
      </div>
</div>