<h2 class="fl-bottom20">Browse projects</h2>

<?php 
if(count ($this->projects) > 0){ ?>

<?php 
$message_unban = "Unban";
$message_ban = "Ban";
?>

<div id="result">
</div>

<div class="fl-cnt-100">		
<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="example">
	<thead>
		<tr>
			<th>Id</th>
			<th>Name</th>
			<th>Author</th>
			<th>Created</th>
			<th>Category</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
<?php 	
	foreach($this->projects as $project){
		?>
		<tr>
			<td><?php echo $project->id?></td>
			<td><?php echo $project->title?></td>
			<td><?php echo $project->user->name?></td>
			<td><?php echo $project->created->format('Y/m/d');?></td>
			<td><?php echo $project->category->name?>		
			</td>
			<td>
				<div class="input-append input-prepend">
			      <a class="btn btn-info" href="/project/index/index/id/<?php echo $project->id?>" title="Go to profile of this project"><i class="icon-picture icon-white"></i> Profile</a><a class="btn btn-info" href="/admin/project/log/id/<?php echo $project->id?>" title="Check the log of this project"><i class="icon-th-list icon-white"></i> Log</a>
			    </div>
			  <?php if($project->ban){?>
				<button class="btn btn-success ban" id="submit_ban" value="<?php echo $project->id?>" title="Unban this project"><?php echo $message_unban?></button>
			<?php }else{ ?>
				<button class="btn btn-danger ban" id="submit_ban" value="<?php echo $project->id?>" title="Ban this project"><?php echo $message_ban?></button>
			<?php }?>
			</td>
		</tr>
		<?php	
	} // end foreach
	?>
	</tbody>
	</table>	
</div>
	
	 <script defer="defer" src="<?=$this->baseUrl('media/data-tables-1.9.1/js/jquery.dataTables.js')?>"></script>
	<script defer="defer" type="text/javascript" charset="utf-8" language="javascript" src="<?=$this->baseUrl('media/data-tables-1.9.1/js/DT_bootstrap.js')?>"></script>
	
	<!-- ban button -->
	 <script defer="defer" type="text/javascript" >
	 $(function(){ // document ready
		 // disable cache
		 $.ajaxSetup ({cache: false });  
		 //  load() functions   
		  var loadUrl = "/admin/project/ajax-ban-project";  
		  
		    $(".ban").click(function(){  
				// send request for changing the user state
		    	var value = $(this).val();
		    	var button = $(this);
		    	
		    	var request = $.ajax({
		    	  url: loadUrl,
		    	  type: "GET",
		    	  data: {id : value},
		    	  dataType: "json"
		    	});

		    	request.done(function(msg) {
					// if is ban
					if(msg.ban){
						button.attr('class', 'btn btn-success ban');
						button.html('<?php echo $message_unban?>');
					}else {
						button.attr('class', 'btn btn-danger ban');
						button.html('<?php echo $message_ban?>');
					}
			    	
		    	   $("#result").html(msg.ban);

		    	});

		    	request.fail(function(jqXHR, textStatus) {
		    	  alert( "Request failed: " + textStatus );
		    	});
		  });  
	 });
	</script> 
<?php } else {
	
	echo "No projects";
	
}?>



