
<?php 
if(count ($this->project) > 0){ ?>

<h3><?php echo $this->project->title; ?>'s log / <a class="btn btn-success" href="/project/index/index/id/<?php echo $this->project->id?>">Project Page</a> </h3>

<div class="fl-cnt-100 fl-top10">
  <a class="btn btn-inverse right" href="/admin/project"><i class="icon-th-list icon-white"></i> Back to all projects</a>
</div>

<div class="fl-cnt-100 fl-top20">
<?php if(count($this->logs) > 0){ ?>

<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="example">
	<thead>
		<tr>
			<th>Created</th>
			<th>Message</th>
			<th>Rate</th>
			<th>Type</th>
		</tr>
	</thead>
	<tbody>

<?php
$total = 0;
	foreach($this->logs as $log){ ?>
	<tr>
		<td><?php echo $log->created->format('Y-m-d/H:i:s')?></td>
			<td><?php echo $log->message?>	</td>
			<td><?php echo $log->rate?>	</td>
			<td><?php echo $log->type?></td>
			<?php $total += $log->rate;?>
	</tr>	
	<?php 	
	} // end of foreach ?>
	<tr><td colspan="2">Total rate is</td><td colspan="2"><strong><?php echo $total;?></strong></td></tr>
	</tbody>
	</table>	

	
<?php 
} else{ echo "No logs messages for this project."; } ?>
</div> 
<?php } else { echo "This project wasn't found."; }?>

